package com.foursoft.etrans.common.util.ejb.sls;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* HomeInterface Class of the com.foursoft.etrans.common.util.ejb.sls.OIDSessionBean *
* Wed Oct 02 16:22:56 IST 2002
* ***********************************************/

/**
 * interface name :OIDSessionHome
 * @author :
 * @version  :1.6
 */
public interface OIDSessionHome extends javax.ejb.EJBHome
{


	 com.foursoft.etrans.common.util.ejb.sls.OIDSession create ()
		throws javax.ejb.CreateException, java.rmi.RemoteException;
}
