/*<%--
 %
 % Copyright (c) 1999-2005 by FourSoft,Pvt Ltd.Reserved.
 % This software is the proprietary information of FourSoft Ltd.
 % Use is subject to license terms.
 % 
 % esupply - v 1.8
 %
--%>

<%--
% File		    :   ETHBLAdvDAO.java
% Sub-Module    :   HBL - Advanced LOV Search. 
% Module        :   ETrans
%
% This is the DAO  for the LOV of the HBLIds based on Different Parameters
% 
% Author        :   G.Srinivas 
% Date 			:   14/03/2005
% Modified date :   14/03/2005
--%>*/

package com.foursoft.esupply.common.dao;

//import com.foursoft.esupply.common.util.Logger;
import org.apache.log4j.Logger;
import com.foursoft.esupply.common.java.ETAdvancedLOVMasterVO;
import com.foursoft.esupply.common.java.ETHBLAdvVO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.ejb.EJBException;

/**
 * 
 */
public class ETHBLAdvDAO extends ETAdvancedLOVMasterDAO
{
  public static String FILE_NAME = "ETHBLAdvDAO.java";
  private static Logger logger = null;

  public ETHBLAdvDAO()
  {
    logger  = Logger.getLogger(ETHBLAdvDAO.class);
  }
  
  /**
   * 
   * @param searchValues
   * @return 
   */
  public  ArrayList getResult(ETAdvancedLOVMasterVO searchValues)
	{  
	   ArrayList details =new ArrayList();
	   
	   String query=null;
	   PreparedStatement pStmt = null;
       Connection connection = null;
       ResultSet rs=null;
       ETHBLAdvVO hblAttributes =null;
	   String searchString =null;
       

	   
     try {
     
			connection = this.getConnection();
			StringBuffer resultQuery= new StringBuffer("");
			StringBuffer selectClause= new StringBuffer("");
			StringBuffer fromClause= new StringBuffer("");
			StringBuffer whereClause= new StringBuffer("");
			hblAttributes = (ETHBLAdvVO)searchValues;


			//Logger.info(FILE_NAME,"...ETHAWBAdvDAO..invokerOperation.@@@@@@.."+hblAttributes.getInvokerOperation());
			//Logger.info(FILE_NAME,"...ETHAWBAdvDAO..Operation....... @@@@@@.."+hblAttributes.getOperation());
			//Logger.info(FILE_NAME,"...ETHAWBAdvDAO...mode...... .....@@@@@@.."+hblAttributes.getMode());
			//Logger.info(FILE_NAME,"...ETHAWBAdvDAO...TerminalType....@@@@@@.."+hblAttributes.getTerminalType());
			//Logger.info(FILE_NAME,"...ETHAWBAdvDAO...operationType...@@@@@@.."+hblAttributes.getOperationType());
			//Logger.info(FILE_NAME,"...ETHAWBAdvDAO...consoleType.....@@@@@@.."+hblAttributes.getConsoleType());


       if (hblAttributes.getInvokerOperation().equals("HBLModify") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@--HBLModify entered....");    
		 //OLD QUERY
		 /*SELECT HOUSEDOCID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.COMPANYNAME CONSIGNEENAME, ORIGINTERMINAL, DESTTERMINAL FROM FS_FR_HOUSEDOCHDR,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE WHERE HOUSEDOCID LIKE '%' AND SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL='DHLHKG' AND MASTERSTATUS='N' AND MASTERDOCID IS NULL AND HOUSEDOCID NOT IN(SELECT  HOUSEDOCID FROM FS_FR_FRTINVOICEMASTER) AND SHIPPER.CUSTOMERID(+) = SHIPPERID AND CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID*/

		  //ADVANCED QUERY
	/*SELECT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID 
	CONSIGNEEID,CONSIGNEE.COMPANYNAME CONSIGNEENAME, ORIGINTERMINAL,DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES , 
	HD.ACTUALVOLUME  FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE  
	WHERE HD.SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL='DHLHKG' AND MASTERSTATUS='N' AND MASTERDOCID 
	IS NULL AND HOUSEDOCID NOT IN(SELECT  HOUSEDOCID FROM FS_FR_FRTINVOICEMASTER) AND SHIPPER.CUSTOMERID(+) = 
	SHIPPERID AND CONSIGNEE.CUSTOMERID(+)=CONSIGNEEID AND SYSDATE- HD.HOUSEDOCDATE  <= 15 ORDER BY HD.HOUSEDOCID DESC */
    
            
		selectClause.append(" SELECT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID, ")
			.append(" SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID CONSIGNEEID,CONSIGNEE.COMPANYNAME ")
			.append(" CONSIGNEENAME, ORIGINTERMINAL,DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES , HD.ACTUALVOLUME "); 
			
		fromClause.append(" FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER,")
			.append(" FS_FR_CUSTOMERMASTER CONSIGNEE ");
			
		whereClause.append(" WHERE HD.SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL= ")
			.append(" '"+hblAttributes.getTerminalID()+"' AND MASTERSTATUS='N' AND MASTERDOCID IS NULL AND ")
			.append(" HOUSEDOCID NOT IN(SELECT  HOUSEDOCID FROM FS_FR_FRTINVOICEMASTER) AND ")
			.append(" SHIPPER.CUSTOMERID(+) = SHIPPERID AND CONSIGNEE.CUSTOMERID(+)=CONSIGNEEID ");

	}	
	else if (hblAttributes.getInvokerOperation().equals("HBLView") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@--HBLView entered....");  
		//OLD QUERY
		//SELECT HOUSEDOCID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.COMPANYNAME CONSIGNEENAME, ORIGINTERMINAL, DESTTERMINAL FROM FS_FR_HOUSEDOCHDR,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE WHERE HOUSEDOCID LIKE '%' AND SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL='DHLHKG' AND SHIPPER.CUSTOMERID(+) = SHIPPERID AND CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID;

		//ADVANCED QUERY
		/*SELECT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID 
		CONSIGNEEID,CONSIGNEE.COMPANYNAME CONSIGNEENAME, ORIGINTERMINAL,DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES ,
		HD.ACTUALVOLUME  
		FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE   
		WHERE HOUSEDOCID LIKE '%' AND HD.SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL='DHLHKG' AND 
		SHIPPER.CUSTOMERID(+) = SHIPPERID AND CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID; */



		selectClause.append(" SELECT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID,")
			.append(" SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID CONSIGNEEID,CONSIGNEE.COMPANYNAME ")
			.append(" CONSIGNEENAME,ORIGINTERMINAL,DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES , HD.ACTUALVOLUME "); 
			
		fromClause.append(" FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER,")
			.append(" FS_FR_CUSTOMERMASTER CONSIGNEE ");
			
		whereClause.append(" WHERE  HD.SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ")
			.append(" ORIGINTERMINAL='"+hblAttributes.getTerminalID()+"' AND SHIPPER.CUSTOMERID(+) = SHIPPERID AND ")
			.append(" CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID ");

   		

	}
	else if (hblAttributes.getInvokerOperation().equals("HBLDelete") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@--HBLDelete entered...."); 
		//OLD QUERY
		//SELECT HOUSEDOCID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.COMPANYNAME CONSIGNEENAME, ORIGINTERMINAL, DESTTERMINAL FROM FS_FR_HOUSEDOCHDR,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE WHERE HOUSEDOCID LIKE '%' AND SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL='DHLHKG' AND MASTERSTATUS='N' AND MASTERDOCID IS NULL AND HOUSEDOCID NOT IN(SELECT  HOUSEDOCID FROM FS_FR_FRTINVOICEMASTER) AND SHIPPER.CUSTOMERID(+) = SHIPPERID AND CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID;
		//ADVANCED QUERY
        /*SELECT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID 
		CONSIGNEEID,CONSIGNEE.COMPANYNAME CONSIGNEENAME, ORIGINTERMINAL,DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES ,
		HD.ACTUALVOLUME  
		FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE  
		WHERE HOUSEDOCID LIKE '%' AND HD.SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL='DHLHKG' AND 
		MASTERSTATUS='N' AND MASTERDOCID IS NULL AND HOUSEDOCID NOT IN(SELECT  HOUSEDOCID FROM FS_FR_FRTINVOICEMASTER) 
		AND SHIPPER.CUSTOMERID(+) = SHIPPERID AND CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID;*/


		selectClause.append(" SELECT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID,")
			.append(" SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID CONSIGNEEID,CONSIGNEE.COMPANYNAME ")
			.append(" CONSIGNEENAME, ORIGINTERMINAL,DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES , HD.ACTUALVOLUME "); 
			
		fromClause.append(" FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER,")
			.append(" FS_FR_CUSTOMERMASTER CONSIGNEE ");
			
		whereClause.append(" WHERE  HD.SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ")
			.append(" ORIGINTERMINAL='"+hblAttributes.getTerminalID()+"' AND MASTERSTATUS='N' AND MASTERDOCID IS NULL ")
			.append(" AND HOUSEDOCID NOT IN(SELECT  HOUSEDOCID FROM FS_FR_FRTINVOICEMASTER) AND SHIPPER.CUSTOMERID(+) ")
			.append(" = SHIPPERID AND CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID ");

	}
else if (hblAttributes.getInvokerOperation().equals("NSIBHBLModify") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@--NSIBHBLModify entered....");    
		 //OLD QUERY
		 /*SELECT HOUSEDOCID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.COMPANYNAME CONSIGNEENAME, ORIGINTERMINAL, DESTTERMINAL FROM FS_FR_HOUSEDOCHDR,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE WHERE HOUSEDOCID LIKE '%' AND SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL IN(SELECT TERMINALID FROM FS_FR_TERMINALMASTER WHERE TERMINALTYPE='N') AND DESTTERMINAL='DHLHKG' AND MASTERDOCID IS NULL AND HOUSEDOCID NOT IN(SELECT HOUSEDOCID FROM FS_FR_FRTINVOICEMASTER) AND SHIPPER.CUSTOMERID(+) = SHIPPERID AND CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID

		  //ADVANCED QUERY
	/*SELECT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID 
	CONSIGNEEID,CONSIGNEE.COMPANYNAME CONSIGNEENAME, ORIGINTERMINAL,DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES , 
	HD.ACTUALVOLUME  FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE WHERE HOUSEDOCID LIKE '%' AND 
HD.SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL IN(SELECT TERMINALID FROM FS_FR_TERMINALMASTER WHERE 
TERMINALTYPE='N') AND DESTTERMINAL='DHLHKG' AND MASTERDOCID IS NULL AND HOUSEDOCID NOT IN(SELECT HOUSEDOCID 
FROM FS_FR_FRTINVOICEMASTER) AND SHIPPER.CUSTOMERID(+) = SHIPPERID AND CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID; */
    
            
		selectClause.append(" SELECT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID, ")
			.append(" SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID CONSIGNEEID,CONSIGNEE.COMPANYNAME ")
			.append(" CONSIGNEENAME, ORIGINTERMINAL,DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES , HD.ACTUALVOLUME "); 
			
		fromClause.append(" FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER,")
			.append(" FS_FR_CUSTOMERMASTER CONSIGNEE ");
			
		whereClause.append(" WHERE HD.SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL ")
			.append(" IN(SELECT TERMINALID FROM FS_FR_TERMINALMASTER WHERE TERMINALTYPE='N') AND DESTTERMINAL= ")
			.append(" '"+hblAttributes.getTerminalID()+"' AND MASTERSTATUS='N' AND MASTERDOCID IS NULL AND ")
			.append(" HOUSEDOCID NOT IN(SELECT  HOUSEDOCID FROM FS_FR_FRTINVOICEMASTER) AND " )
			.append(" SHIPPER.CUSTOMERID(+) = SHIPPERID AND CONSIGNEE.CUSTOMERID(+)=CONSIGNEEID ");

  
	}	
	else if (hblAttributes.getInvokerOperation().equals("NSIBHBLView") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@--NSIBHBLView entered....");  
		//OLD QUERY
		//SELECT HOUSEDOCID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.COMPANYNAME CONSIGNEENAME, ORIGINTERMINAL, DESTTERMINAL FROM FS_FR_HOUSEDOCHDR,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE WHERE HOUSEDOCID LIKE '%' AND SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL IN(SELECT TERMINALID FROM FS_FR_TERMINALMASTER WHERE TERMINALTYPE='N') AND DESTTERMINAL='DHLHKG' AND MASTERSTATUS='N' AND HOUSEDOCID NOT IN(SELECT HOUSEDOCID FROM FS_FR_FRTINVOICEMASTER) AND SHIPPER.CUSTOMERID(+) = SHIPPERID AND CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID

		//ADVANCED QUERY
		/*SELECT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID 
		CONSIGNEEID,CONSIGNEE.COMPANYNAME CONSIGNEENAME, ORIGINTERMINAL,DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES ,
		HD.ACTUALVOLUME  
		FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE  
		WHERE HOUSEDOCID LIKE '%' AND HD.SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL IN(SELECT TERMINALID 
		FROM FS_FR_TERMINALMASTER WHERE TERMINALTYPE='N') AND DESTTERMINAL='DHLHKG' AND SHIPPER.CUSTOMERID(+) = 
		SHIPPERID AND CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID; */


		selectClause.append(" SELECT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID,SHIPPER.COMPANYNAME SHIPPERNAME,")
			.append(" CONSIGNEE.CUSTOMERID CONSIGNEEID,CONSIGNEE.COMPANYNAME CONSIGNEENAME,ORIGINTERMINAL,DESTTERMINAL,")
			.append(" HD.GROSSWEIGHT , HD.TOTPIECES , HD.ACTUALVOLUME "); 
			
		fromClause.append(" FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER,")
			.append(" FS_FR_CUSTOMERMASTER CONSIGNEE ");
			
		whereClause.append(" WHERE  HD.SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL IN(SELECT TERMINALID ")
		.append(" FROM FS_FR_TERMINALMASTER WHERE TERMINALTYPE='N') AND DESTTERMINAL='"+hblAttributes.getTerminalID()+"' AND SHIPPER.CUSTOMERID(+) = SHIPPERID AND ")
			.append(" CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID ");


	}
	else if (hblAttributes.getInvokerOperation().equals("NSIBHBLDelete") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@--NSIBHBLDelete entered...."); 
		//OLD QUERY
		//SELECT HOUSEDOCID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.COMPANYNAME CONSIGNEENAME, ORIGINTERMINAL, DESTTERMINAL FROM FS_FR_HOUSEDOCHDR,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE WHERE HOUSEDOCID LIKE '%' AND SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL='DHLHKG' AND MASTERSTATUS='N' AND MASTERDOCID IS NULL AND HOUSEDOCID NOT IN(SELECT  HOUSEDOCID FROM FS_FR_FRTINVOICEMASTER) AND SHIPPER.CUSTOMERID(+) = SHIPPERID AND CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID;
		//ADVANCED QUERY
        /*SELECT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID 
		CONSIGNEEID,CONSIGNEE.COMPANYNAME CONSIGNEENAME, ORIGINTERMINAL,DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES ,
		HD.ACTUALVOLUME  
		FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE  
		
		WHERE HOUSEDOCID LIKE '%' AND HD.SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL IN(SELECT TERMINALID 
		FROM FS_FR_TERMINALMASTER WHERE TERMINALTYPE='N') AND DESTTERMINAL='DHLHKG' AND MASTERSTATUS='N' AND 
		HOUSEDOCID NOT IN(SELECT HOUSEDOCID FROM FS_FR_FRTINVOICEMASTER) AND SHIPPER.CUSTOMERID(+) = SHIPPERID 
		AND CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID;*/


		selectClause.append(" SELECT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID,")
			.append(" SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID CONSIGNEEID,CONSIGNEE.COMPANYNAME ")
			.append(" CONSIGNEENAME, ORIGINTERMINAL,DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES , HD.ACTUALVOLUME "); 
			
		fromClause.append(" FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER,")
			.append(" FS_FR_CUSTOMERMASTER CONSIGNEE ");
			
		whereClause.append(" WHERE  HD.SHIPMENTMODE=2 AND DIRECTCONSOLE='N' AND ORIGINTERMINAL ")
			.append(" IN(SELECT TERMINALID FROM FS_FR_TERMINALMASTER WHERE TERMINALTYPE='N') AND ")
			.append(" DESTTERMINAL='"+hblAttributes.getTerminalID()+"' AND MASTERSTATUS='N'  ")
			.append(" AND HOUSEDOCID NOT IN(SELECT  HOUSEDOCID FROM FS_FR_FRTINVOICEMASTER) AND SHIPPER.CUSTOMERID(+) ")
			.append(" = SHIPPERID AND CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID ");

	}
	// View/Print/Attach Doc  * NSIB View / Print
	else if (hblAttributes.getInvokerOperation().equals("HBLDocument")||hblAttributes.getInvokerOperation().equals("HBLPrint")||hblAttributes.getInvokerOperation().equals("HBLAttach")||hblAttributes.getInvokerOperation().equals("NSIBHBLDocument")||hblAttributes.getInvokerOperation().equals("NSIBHBLPrint") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@--HBLDocument entered....");
		
		//OLD QUERY
		//SELECT DISTINCT HOUSEDOCID  FROM FS_FR_HOUSEDOCHDR   WHERE  ORIGINTERMINAL='DHLHKG'  AND SHIPMENTMODE=2 AND HOUSEDOCID LIKE '%' 
		//ADVANCED QUERY

		/*SELECT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID, SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID CONSIGNEEID,
CONSIGNEE.COMPANYNAME CONSIGNEENAME,ORIGINTERMINAL,DESTTERMINAL, HD.GROSSWEIGHT , HD.TOTPIECES ,HD.ACTUALVOLUME  
FROM  
 FS_FR_HOUSEDOCHDR HD,   
 FS_FR_CUSTOMERMASTER SHIPPER, 
 FS_FR_CUSTOMERMASTER CONSIGNEE 
WHERE 
 HD.SHIPPERID = SHIPPER.CUSTOMERID 
 AND HD.CONSIGNEEID  = CONSIGNEE.CUSTOMERID 
 AND ORIGINTERMINAL='DHLHKG' 
 AND SHIPMENTMODE=1 
ORDER BY 
 HOUSEDOCID DESC;
*/

    selectClause.append(" SELECT DISTINCT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID,")
										.append(" SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID CONSIGNEEID,")
										.append(" CONSIGNEE.COMPANYNAME CONSIGNEENAME,HD.ORIGINTERMINAL,HD.DESTTERMINAL, ")
										.append(" HD.GROSSWEIGHT , HD.TOTPIECES ,HD.ACTUALVOLUME "); 
			
	fromClause.append(" FROM  FS_FR_HOUSEDOCHDR HD,   FS_FR_CUSTOMERMASTER SHIPPER,")
									.append(" FS_FR_CUSTOMERMASTER CONSIGNEE ");
			
	whereClause.append(" WHERE  HD.ORIGINTERMINAL ='"+hblAttributes.getTerminalID()+"' ")
									.append(" AND HD.SHIPMENTMODE =2  AND HD.SHIPPERID = SHIPPER.CUSTOMERID ")
									.append(" AND HD.CONSIGNEEID  = CONSIGNEE.CUSTOMERID  ");

	}
	else if (hblAttributes.getInvokerOperation().equals("HBLWHAdd") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@--HBLWHAdd  entered...."); 

//OLD QUERY
		//SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE HOUSEDOCID LIKE '%' AND TERMINALID= 'DHLHKG' AND ORIGINTERMINAL ='DHLHKG' AND SHIPMENTMODE=2
//ADVANCED QUERY
		/*SELECT DISTINCT RP.HAWB_ID,SHIPPER.CUSTOMERID SHIPPERID, SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID 
CONSIGNEEID, CONSIGNEE.COMPANYNAME CONSIGNEENAME,HD.ORIGINTERMINAL,HD.DESTTERMINAL,  HD.GROSSWEIGHT , HD.TOTPIECES 
,HD.ACTUALVOLUME 
FROM FS_RT_PLAN RP, FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE   
WHERE RP.HAWB_ID = HD.HOUSEDOCID AND HD.SHIPPERID = SHIPPER.CUSTOMERID  AND HD.CONSIGNEEID  = CONSIGNEE.CUSTOMERID
AND HD.SHIPPERID = RP.SHIPPER_ID  AND HD.CONSIGNEEID  = RP.CONSIGNEE_ID AND  HD.SHIPMENTMODE=2 
AND RP.HAWB_ID = HD.HOUSEDOCID  AND RP.PRMY_MODE = 2 AND  HD.HOUSEDOCID 
NOT IN (SELECT BOOKINGID FROM FS_FR_WHMASTER WHERE OPERATIONTYPE='Destination' )  
AND  RP.HAWB_ID IN ( SELECT A.HAWB_ID FROM FS_RT_PLAN A, FS_RT_LEG B,FS_FRS_CONSOLEMASTER M,
FS_FR_MASTERDOCHDR R  WHERE A.RT_PLAN_ID = B.RT_PLAN_ID  AND ROUND( TO_DATE('21-03-05 23:39', 'DD-MM-YY HH24:MI') 
- B.RECEIVED_DATE) < 15 AND A.DEST_TRML_ID = 'DHLHKG' AND  (     ( B.MSTER_DOC_ID= M.CONSOLEID        
AND M.CONSOLTYPE NOT IN('FCL_BACK_TO_BACK','BREAK_BULK') 	  )     OR     
(         B.LEG_TYPE ='GT' AND B.AUTO_MNUL_FLAG='M'      ) 	  OR       
(   		 B.MSTER_DOC_ID= R.MASTERDOCID  	   )    )  AND 
((B.LEG_TYPE IN ('TP','GT','TG') AND B.SHPMNT_STATUS IN ('P','B')) OR 
(B.LEG_TYPE ='GT' AND B.AUTO_MNUL_FLAG='M')) AND ( ((SELECT SUM(BOXESRELEASEDCURR) 
FROM FS_FR_DELIVERYORDER WHERE HOUSEDOCNO=RP.HAWB_ID) < B.PIECES_RECEIVED ) 
OR ((SELECT COUNT(HOUSEDOCNO) FROM FS_FR_DELIVERYORDER WHERE HOUSEDOCNO=RP.HAWB_ID) = 0) ) ) 
AND RP.HAWB_ID LIKE '%' ;
*/


		selectClause.append(" SELECT  RP.HAWB_ID,SHIPPER.CUSTOMERID SHIPPERID, ")
										.append(" SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID ")
										.append(" CONSIGNEEID, CONSIGNEE.COMPANYNAME CONSIGNEENAME,")
										.append(" HD.ORIGINTERMINAL,HD.DESTTERMINAL,  HD.GROSSWEIGHT , ")
										.append(" HD.TOTPIECES ,HD.ACTUALVOLUME  "); 
			
	fromClause.append(" FROM FS_RT_PLAN RP, FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER ")
										.append(" SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE ");
			
	whereClause.append(" WHERE RP.HAWB_ID = HD.HOUSEDOCID AND HD.SHIPPERID = ")
		.append(" SHIPPER.CUSTOMERID  AND HD.CONSIGNEEID  = CONSIGNEE.CUSTOMERID AND HD.SHIPPERID = RP.SHIPPER_ID  ")
		.append(" AND HD.CONSIGNEEID  =  RP.CONSIGNEE_ID  AND  HD.SHIPMENTMODE=2 AND RP.HAWB_ID = HD.HOUSEDOCID  ")
		.append(" AND RP.PRMY_MODE = 2 AND  HD.HOUSEDOCID NOT IN (SELECT BOOKINGID FROM FS_FR_WHMASTER WHERE ")
		.append(" OPERATIONTYPE='Destination' )  AND  RP.HAWB_ID IN ( SELECT A.HAWB_ID FROM FS_RT_PLAN A, ")
		.append(" FS_RT_LEG B,FS_FRS_CONSOLEMASTER M,FS_FR_MASTERDOCHDR R  WHERE A.RT_PLAN_ID = B.RT_PLAN_ID  AND ")
		.append(" A.DEST_TRML_ID = '"+hblAttributes.getTerminalID()+"' AND ( ( B.MSTER_DOC_ID= M.CONSOLEID AND M.CONSOLTYPE NOT IN ")
		.append(" ('FCL_BACK_TO_BACK','BREAK_BULK') ) OR ( B.LEG_TYPE ='GT' AND B.AUTO_MNUL_FLAG='M' ) OR ")
		.append(" ( B.MSTER_DOC_ID= R.MASTERDOCID ) ) AND ((B.LEG_TYPE IN ('TP','GT','TG') AND B.SHPMNT_STATUS IN ")
		.append(" ('P','B')) OR (B.LEG_TYPE ='GT' AND B.AUTO_MNUL_FLAG='M')) AND ( ((SELECT SUM(BOXESRELEASEDCURR) ")
		.append(" FROM FS_FR_DELIVERYORDER WHERE HOUSEDOCNO=RP.HAWB_ID) < B.PIECES_RECEIVED ) OR ")
		.append(" ((SELECT COUNT(HOUSEDOCNO) FROM FS_FR_DELIVERYORDER WHERE HOUSEDOCNO=RP.HAWB_ID) = 0) ) ) ");

    
	}

	else if (hblAttributes.getInvokerOperation().equals("HBLWHModify") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@--HBLWHModify entered...."); 

		//OLD QUERY
		//SELECT DISTINCT HOUSEDOCID  FROM FS_FR_HOUSEDOCHDR   WHERE  ORIGINTERMINAL='DHLHKG'  AND SHIPMENTMODE=2 AND HOUSEDOCID LIKE '%' 
		//ADVANCED QUERY
		/*SELECT 	DISTINCT RP.HAWB_ID, WH.WAREHOUSEID,SHIPPER.CUSTOMERID SHIPPERID, SHIPPER.COMPANYNAME SHIPPERNAME,
CONSIGNEE.CUSTOMERID CONSIGNEEID, CONSIGNEE.COMPANYNAME CONSIGNEENAME,HD.ORIGINTERMINAL,HD.DESTTERMINAL,  
HD.GROSSWEIGHT , HD.TOTPIECES,HD.ACTUALVOLUME
FROM FS_RT_PLAN RP, FS_FR_HOUSEDOCHDR HD, FS_FR_WHMASTER WH,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE   

WHERE RP.HAWB_ID = HD.HOUSEDOCID AND WH.BOOKINGID = HD.HOUSEDOCID AND HD.SHIPPERID = SHIPPER.CUSTOMERID  AND 
HD.CONSIGNEEID  = CONSIGNEE.CUSTOMERID AND HD.SHIPPERID = RP.SHIPPER_ID  AND HD.CONSIGNEEID  = RP.CONSIGNEE_ID AND 
HD.SHIPMENTMODE=2   AND HD.WHSTATUS = 'PD' AND 
WH.OPERATIONTYPE ='Destination' AND RP.PRMY_MODE = 2 AND  WH.BOOKINGID NOT IN (SELECT  HOUSEDOCNO FROM 
FS_FR_DELIVERYORDER  WHERE   SHIPMENTMODE =2) AND RP.HAWB_ID IN ( SELECT A.HAWB_ID FROM FS_RT_PLAN A, 
FS_RT_LEG B WHERE A.RT_PLAN_ID = B.RT_PLAN_ID AND A.DEST_TRML_ID = 'DHLHKG'  AND ((B.LEG_TYPE IN ('TP','GT','TG') 
AND B.SHPMNT_STATUS IN ('P','B')) OR (B.LEG_TYPE ='GT' AND B.AUTO_MNUL_FLAG='M')) AND 
( ( (SELECT SUM(BOXESRELEASEDCURR) FROM FS_FR_DELIVERYORDER WHERE HOUSEDOCNO=RP.HAWB_ID) < B.PIECES_RECEIVED ) 
OR ( (SELECT COUNT(HOUSEDOCNO) FROM FS_FR_DELIVERYORDER WHERE HOUSEDOCNO=RP.HAWB_ID) = 0 ) ) AND 
( (SELECT SUM(BOXESRECEIVED) FROM FS_FR_WHMASTER WHERE BOOKINGID=RP.HAWB_ID AND OPERATIONTYPE ='Destination')
< B.PIECES_RECEIVED ) ) AND ROUND( TO_DATE('21-03-05 23:40', 'DD-MM-YY HH24:MI') - HD.HOUSEDOCDATE) < 15 
AND RP.HAWB_ID LIKE '%' ;
*/


	selectClause.append(" SELECT  RP.HAWB_ID,SHIPPER.CUSTOMERID SHIPPERID, ")
										.append(" SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID ")
										.append(" CONSIGNEEID, CONSIGNEE.COMPANYNAME CONSIGNEENAME,")
										.append(" HD.ORIGINTERMINAL,HD.DESTTERMINAL,  HD.GROSSWEIGHT , ")
										.append(" HD.TOTPIECES ,HD.ACTUALVOLUME , WH.WAREHOUSEID "); 
			
	fromClause.append(" FROM FS_RT_PLAN RP, FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER ")
										.append(" SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE, FS_FR_WHMASTER WH ");
			
	whereClause.append(" WHERE RP.HAWB_ID = HD.HOUSEDOCID AND WH.BOOKINGID = HD.HOUSEDOCID ")
		.append(" AND HD.SHIPPERID = SHIPPER.CUSTOMERID  AND HD.CONSIGNEEID  = CONSIGNEE.CUSTOMERID AND HD.SHIPPERID ")
		.append(" = RP.SHIPPER_ID  AND HD.CONSIGNEEID  = RP.CONSIGNEE_ID  AND HD.SHIPMENTMODE=2  AND HD.WHSTATUS =")
		.append(" 'PD' AND WH.OPERATIONTYPE ='Destination' AND RP.PRMY_MODE = 2 AND  WH.BOOKINGID NOT IN ")
		.append(" (SELECT  HOUSEDOCNO FROM FS_FR_DELIVERYORDER  WHERE   SHIPMENTMODE =2) AND RP.HAWB_ID IN ")
		.append(" ( SELECT A.HAWB_ID FROM FS_RT_PLAN A,FS_RT_LEG B WHERE A.RT_PLAN_ID = B.RT_PLAN_ID AND ")
		.append(" A.DEST_TRML_ID = '"+hblAttributes.getTerminalID()+"'  AND ((B.LEG_TYPE IN ('TP','GT','TG')AND ")
		.append(" B.SHPMNT_STATUS IN ('P','B')) OR (B.LEG_TYPE ='GT' AND B.AUTO_MNUL_FLAG='M')) AND ( ( ")
		.append(" (SELECT SUM(BOXESRELEASEDCURR) FROM FS_FR_DELIVERYORDER WHERE HOUSEDOCNO=RP.HAWB_ID) < B.PIECES_RECEIVED ) OR ")
		.append(" ( (SELECT COUNT(HOUSEDOCNO) FROM FS_FR_DELIVERYORDER WHERE HOUSEDOCNO=RP.HAWB_ID) = 0 ) ) AND ")
		.append(" ( (SELECT SUM(BOXESRECEIVED) FROM FS_FR_WHMASTER WHERE BOOKINGID=RP.HAWB_ID AND OPERATIONTYPE =")
		.append(" 'Destination') < B.PIECES_RECEIVED ) ) ");
   			

	}
	
	else if (hblAttributes.getInvokerOperation().equals("HBLWHView") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@--HBLWHView entered...."); 

		//OLD QUERY
		//SELECT DISTINCT HOUSEDOCID  FROM FS_FR_HOUSEDOCHDR   WHERE  DESTTERMINAL='DHLHKG'  AND SHIPMENTMODE=2 AND HOUSEDOCID LIKE '%' 
		//ADVANCED QUERY
		
		/*SELECT 	DISTINCT RP.HAWB_ID,SHIPPER.CUSTOMERID SHIPPERID,  SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID 
CONSIGNEEID, CONSIGNEE.COMPANYNAME CONSIGNEENAME, HD.ORIGINTERMINAL,HD.DESTTERMINAL,  HD.GROSSWEIGHT ,  HD.TOTPIECES ,
HD.ACTUALVOLUME , WH.WAREHOUSEID 
FROM FS_RT_PLAN RP, FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER  SHIPPER,FS_FR_CUSTOMERMASTER CONSIGNEE, FS_FR_WHMASTER WH 
WHERE RP.HAWB_ID = HD.HOUSEDOCID AND WH.BOOKINGID = HD.HOUSEDOCID 
AND HD.SHIPPERID = SHIPPER.CUSTOMERID  AND HD.CONSIGNEEID  = CONSIGNEE.CUSTOMERID AND HD.SHIPPERID  = RP.SHIPPER_ID  
AND HD.CONSIGNEEID  = RP.CONSIGNEE_ID AND HD.SHIPMENTMODE=2 AND RP.HAWB_ID = HD.HOUSEDOCID AND 
WH.BOOKINGID = HD.HOUSEDOCID AND HD.WHSTATUS IN ('PD','CD')  AND WH.OPERATIONTYPE='Destination' AND 
RP.PRMY_MODE = 2 AND RP.HAWB_ID IN ( SELECT A.HAWB_ID FROM FS_RT_PLAN A, FS_RT_LEG B WHERE 
A.RT_PLAN_ID = B.RT_PLAN_ID AND A.DEST_TRML_ID = 'DHLHKG'  AND ((B.LEG_TYPE IN ('TP','GT','TG') AND B.SHPMNT_STATUS 
IN ('P','B')) OR (B.LEG_TYPE ='GT' AND B.AUTO_MNUL_FLAG='M')) ) AND 
ROUND( TO_DATE('21-03-05 23:40', 'DD-MM-YY HH24:MI') - HD.HOUSEDOCDATE) < 15 AND RP.HAWB_ID LIKE '%' ;
*/


	selectClause.append(" SELECT  RP.HAWB_ID,SHIPPER.CUSTOMERID SHIPPERID, ")
										.append(" SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID ")
										.append(" CONSIGNEEID, CONSIGNEE.COMPANYNAME CONSIGNEENAME,")
										.append(" HD.ORIGINTERMINAL,HD.DESTTERMINAL,  HD.GROSSWEIGHT , ")
										.append(" HD.TOTPIECES ,HD.ACTUALVOLUME , WH.WAREHOUSEID "); 
			
	fromClause.append(" FROM FS_RT_PLAN RP, FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER ")
										.append(" SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE, FS_FR_WHMASTER WH ");
			
	whereClause.append(" WHERE RP.HAWB_ID = HD.HOUSEDOCID AND WH.BOOKINGID = HD.HOUSEDOCID ")
		.append(" AND HD.SHIPPERID = SHIPPER.CUSTOMERID  AND HD.CONSIGNEEID  = CONSIGNEE.CUSTOMERID AND HD.SHIPPERID ")
		.append(" = RP.SHIPPER_ID  AND HD.CONSIGNEEID  = RP.CONSIGNEE_ID AND HD.SHIPMENTMODE=2 AND RP.HAWB_ID = ")
		.append(" HD.HOUSEDOCID AND WH.BOOKINGID = HD.HOUSEDOCID AND HD.WHSTATUS IN ('PD','CD')  AND ")
		.append(" WH.OPERATIONTYPE='Destination' AND RP.PRMY_MODE = 2 AND RP.HAWB_ID IN ( SELECT A.HAWB_ID FROM ")
		.append(" FS_RT_PLAN A, FS_RT_LEG B WHERE A.RT_PLAN_ID = B.RT_PLAN_ID AND A.DEST_TRML_ID = ")
		.append(" '"+hblAttributes.getTerminalID()+"'  AND ((B.LEG_TYPE IN ('TP','GT','TG') AND B.SHPMNT_STATUS IN ")
		.append(" ('P','B')) OR (B.LEG_TYPE ='GT' AND B.AUTO_MNUL_FLAG='M')) ) ");

	}
	else if (hblAttributes.getInvokerOperation().equals("HBLWHDelete") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@--HBLWHDelete entered...."); 

//OLD QUERY
		//SELECT DISTINCT HOUSEDOCID  FROM FS_FR_HOUSEDOCHDR   WHERE  DESTTERMINAL='DHLHKG'  AND SHIPMENTMODE=2 AND HOUSEDOCID LIKE '%' 
		//ADVANCED QUERY
/*SELECT 	DISTINCT RP.HAWB_ID,SHIPPER.CUSTOMERID SHIPPERID,  SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID  
CONSIGNEEID, CONSIGNEE.COMPANYNAME CONSIGNEENAME, HD.ORIGINTERMINAL,HD.DESTTERMINAL,  HD.GROSSWEIGHT ,  HD.TOTPIECES ,
HD.ACTUALVOLUME , WH.WAREHOUSEID 
FROM FS_RT_PLAN RP,FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE,FS_FR_WHMASTER WH 
WHERE RP.HAWB_ID = HD.HOUSEDOCID AND WH.BOOKINGID = HD.HOUSEDOCID  AND HD.SHIPPERID = SHIPPER.CUSTOMERID  AND 
HD.CONSIGNEEID  = CONSIGNEE.CUSTOMERID AND HD.SHIPPERID  = RP.SHIPPER_ID  AND HD.CONSIGNEEID  = RP.CONSIGNEE_ID 
AND WH.SHIPMENTMODE=2 AND  WH.OPERATIONTYPE ='Destination'  AND  HD.WHSTATUS IN ('PD','CD') AND  WH.BOOKINGID = 
HD.HOUSEDOCID AND  WH.TERMINALID='DHLHKG'  AND WH.BOOKINGID NOT IN(SELECT HOUSEDOCNO  FROM  FS_FR_DELIVERYORDER )  
AND ROUND( TO_DATE('21-03-05 23:40', 'DD-MM-YY HH24:MI') - HD.HOUSEDOCDATE) < 15 ;
*/


	selectClause.append(" SELECT  RP.HAWB_ID,SHIPPER.CUSTOMERID SHIPPERID, ")
										.append(" SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID ")
										.append(" CONSIGNEEID, CONSIGNEE.COMPANYNAME CONSIGNEENAME,")
										.append(" HD.ORIGINTERMINAL,HD.DESTTERMINAL,  HD.GROSSWEIGHT , ")
										.append(" HD.TOTPIECES ,HD.ACTUALVOLUME , WH.WAREHOUSEID "); 
			
	fromClause.append(" FROM FS_RT_PLAN RP, FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER ")
										.append(" SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE, FS_FR_WHMASTER WH ");
			
	whereClause.append(" WHERE RP.HAWB_ID = HD.HOUSEDOCID AND WH.BOOKINGID = HD.HOUSEDOCID  ")
		.append(" AND HD.SHIPPERID = SHIPPER.CUSTOMERID  AND HD.CONSIGNEEID  = CONSIGNEE.CUSTOMERID AND HD.SHIPPERID ")
		.append(" = RP.SHIPPER_ID  AND HD.CONSIGNEEID  = RP.CONSIGNEE_ID AND WH.SHIPMENTMODE=2 AND  WH.OPERATIONTYPE ")
		.append(" ='Destination'  AND  HD.WHSTATUS IN ('PD','CD') AND  WH.BOOKINGID = HD.HOUSEDOCID AND  ")
		.append(" WH.TERMINALID='"+hblAttributes.getTerminalID()+"'  AND WH.BOOKINGID NOT IN(SELECT HOUSEDOCNO  ")
		.append(" FROM  FS_FR_DELIVERYORDER ) ");


	}

	else if (hblAttributes.getInvokerOperation().equals("HBLActivityAdd") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@--HBLActivityAdd entered...."); 

//OLD QUERY
//SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE SHIPMENTMODE=2 AND ORIGINTERMINAL='DHLHKG' AND HOUSEDOCID NOT IN(SELECT DOCID FROM FS_FR_HOUSEACTIVITYDTL) AND RECEIPTSTATUS IS NULL  AND HOUSEDOCID LIKE '%' ORDER BY HOUSEDOCID;
//ADVANCED QUERY
/*SELECT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID 
CONSIGNEEID,CONSIGNEE.COMPANYNAME CONSIGNEENAME, ORIGINTERMINAL,DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES , 
HD.ACTUALVOLUME  FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE  WHERE  
HD.SHIPPERID = SHIPPER.CUSTOMERID  AND HD.CONSIGNEEID  = CONSIGNEE.CUSTOMERID AND SHIPMENTMODE=2 AND 
ORIGINTERMINAL='"+hblAttributes.getTerminalID()+"' AND HOUSEDOCID NOT IN(SELECT DOCID FROM FS_FR_HOUSEACTIVITYDTL) 
AND RECEIPTSTATUS IS NULL  
AND HOUSEDOCID LIKE '%' ORDER BY HOUSEDOCID;*/


	selectClause.append(" SELECT HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID, ")
				.append(" SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID ")
				.append(" CONSIGNEEID, CONSIGNEE.COMPANYNAME CONSIGNEENAME,")
				.append(" HD.ORIGINTERMINAL,HD.DESTTERMINAL,  HD.GROSSWEIGHT , ")
				.append(" HD.TOTPIECES ,HD.ACTUALVOLUME  "); 
			
	fromClause.append(" FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER,FS_FR_CUSTOMERMASTER CONSIGNEE ");
			
	whereClause.append(" WHERE  HD.SHIPPERID = SHIPPER.CUSTOMERID  AND HD.CONSIGNEEID  = CONSIGNEE.CUSTOMERID AND ")
		       .append(" HD.SHIPMENTMODE=2 AND ORIGINTERMINAL='"+hblAttributes.getTerminalID()+"' AND ")
			   .append(" HOUSEDOCID NOT IN(SELECT DOCID FROM FS_FR_HOUSEACTIVITYDTL) AND RECEIPTSTATUS IS NULL ");
	}
else if (hblAttributes.getInvokerOperation().equals("HBLActivityModify")||hblAttributes.getInvokerOperation().equals("HBLActivityView")||hblAttributes.getInvokerOperation().equals("HBLActivityDelete") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@-- entered :"+hblAttributes.getInvokerOperation()); 

//OLD QUERY
//SELECT DOCID FROM FS_FR_HOUSEACTIVITYHDR WHERE DOCTYPE='H' AND SHIPMENTMODE=2 AND TERMINALID='DHLHKG';
//ADVANCED QUERY
/*SELECT DOCID,SHIPPER.CUSTOMERID SHIPPERID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID 
CONSIGNEEID,CONSIGNEE.COMPANYNAME CONSIGNEENAME, ORIGINTERMINAL,DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES , 
HD.ACTUALVOLUME  
FROM FS_FR_HOUSEACTIVITYHDR HA ,FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER, 
FS_FR_CUSTOMERMASTER CONSIGNEE  
WHERE  HD.HOUSEDOCID=HA.DOCID AND
HD.SHIPPERID = SHIPPER.CUSTOMERID  AND HD.CONSIGNEEID  = CONSIGNEE.CUSTOMERID  AND HA.DOCTYPE='H' AND 
HA.SHIPMENTMODE=2 AND HA.TERMINALID='"+hblAttributes.getTerminalID()+"';*/

	selectClause.append(" SELECT DOCID,SHIPPER.CUSTOMERID SHIPPERID, ")
				.append(" SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID ")
				.append(" CONSIGNEEID, CONSIGNEE.COMPANYNAME CONSIGNEENAME,")
				.append(" HD.ORIGINTERMINAL,HD.DESTTERMINAL,  HD.GROSSWEIGHT , ")
				.append(" HD.TOTPIECES ,HD.ACTUALVOLUME  "); 
			
	fromClause.append(" FROM FS_FR_HOUSEACTIVITYHDR HA , FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER ")
			  .append(" SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE ");
			
	whereClause.append(" WHERE  HD.HOUSEDOCID=HA.DOCID AND HD.SHIPPERID = SHIPPER.CUSTOMERID  AND HD.CONSIGNEEID  = ")
		       .append(" CONSIGNEE.CUSTOMERID  AND HA.DOCTYPE='H' AND HA.SHIPMENTMODE=2 AND ")
		       .append(" HA.TERMINALID='"+hblAttributes.getTerminalID()+"' ");
	}

else if (hblAttributes.getInvokerOperation().equals("HBLChargesOriginAdd")||hblAttributes.getInvokerOperation().equals("HBLChargesOriginModify")||hblAttributes.getInvokerOperation().equals("HBLChargesOriginDelete") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@-- entered :"+hblAttributes.getInvokerOperation()); 

//OLD QUERY
//SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE  ORIGINTERMINAL='DHLHKG'  AND ROUND(TO_DATE('23/03/2005 13:03','DD/MM/YYYY HH24:MI') -HOUSEDOCDATE ) < 15  AND (ORIGINSTATUS IS NULL OR ORIGINSTATUS!= 'F' OR DESTINATIONSTATUS  IS NULL OR DESTINATIONSTATUS !='F') AND SHIPMENTMODE =2 AND HOUSEDOCID LIKE '%' UNION 	SELECT CONSOLEID FROM FS_FRS_CONSOLEMASTER  WHERE 	DIRECTCONSOLE='Y' AND ORIGINTERMINAL='DHLHKG' AND  ORIGINSTATUS IS NULL AND (ORIGINSTATUS IS NULL OR ORIGINSTATUS !='F')  AND ROUND(TO_DATE('23/03/2005 13:03','DD/MM/YYYY HH24:MI') -CONSOLEDATE ) < 15   AND CONSOLEID LIKE '%' ;

//ADVANCED QUERY
/*SELECT 

 A.HOUSEDOCID ,

 HD.ORIGINTERMINAL ,

 HD.DESTTERMINAL ,

 HD.GROSSWEIGHT,

 HD.TOTPIECES,

 HD.ACTUALVOLUME ,

 SHIPPER.CUSTOMERID SHIPPERID  , 

 SHIPPER.COMPANYNAME SHIPPERNAME ,

 CONSIGNEE.CUSTOMERID CONSIGNEEID , 

 CONSIGNEE.COMPANYNAME  CONSIGNEENAME

FROM 

(

SELECT 

 HOUSEDOCID 

FROM 

 FS_FR_HOUSEDOCHDR 

WHERE  

 ORIGINTERMINAL='"+hblAttributes.getTerminalID()+"'  

AND (

   ORIGINSTATUS IS NULL OR ORIGINSTATUS!= 'F' 

   OR DESTINATIONSTATUS  IS NULL OR DESTINATIONSTATUS !='F'

  ) 

 AND SHIPMENTMODE =2 

UNION  

SELECT 

 CONSOLEID 

FROM 

 FS_FRS_CONSOLEMASTER  

WHERE  

 DIRECTCONSOLE='Y' 

 AND ORIGINTERMINAL='"+hblAttributes.getTerminalID()+"' 

 AND  ORIGINSTATUS IS NULL 

 AND (ORIGINSTATUS IS NULL OR ORIGINSTATUS !='F')  

) A, FS_FR_HOUSEDOCHDR HD,

 FS_FR_CUSTOMERMASTER SHIPPER,

  FS_FR_CUSTOMERMASTER CONSIGNEE 

WHERE 

 A.HOUSEDOCID = HD.HOUSEDOCID(+)

AND HD.SHIPPERID = SHIPPER.CUSTOMERID(+) 

  AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+);*/


  selectClause.append("SELECT A.HOUSEDOCID , HD.ORIGINTERMINAL , HD.DESTTERMINAL , HD.GROSSWEIGHT, HD.TOTPIECES, HD.ACTUALVOLUME , SHIPPER.CUSTOMERID SHIPPERID  , SHIPPER.COMPANYNAME SHIPPERNAME , CONSIGNEE.CUSTOMERID CONSIGNEEID ,  CONSIGNEE.COMPANYNAME  CONSIGNEENAME   ");

fromClause.append(" FROM (SELECT  HOUSEDOCID FROM  FS_FR_HOUSEDOCHDR WHERE  ORIGINTERMINAL= '");
fromClause.append(hblAttributes.getTerminalID());
fromClause.append("' ");  
fromClause.append(" AND ( ORIGINSTATUS IS NULL OR ORIGINSTATUS!= 'F' OR DESTINATIONSTATUS  IS NULL OR DESTINATIONSTATUS !='F'  ) AND SHIPMENTMODE =2 UNION  SELECT  CONSOLEID FROM  FS_FRS_CONSOLEMASTER  WHERE   DIRECTCONSOLE='Y' AND  ORIGINTERMINAL= '");

fromClause.append(hblAttributes.getTerminalID());
fromClause.append("' ");
fromClause.append(" AND  ORIGINSTATUS IS NULL  AND (ORIGINSTATUS IS NULL OR ORIGINSTATUS !='F')  ) A ,");

fromClause.append(" FS_FR_HOUSEDOCHDR HD, FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE ");

whereClause.append(" WHERE  A.HOUSEDOCID = HD.HOUSEDOCID(+) AND HD.SHIPPERID = SHIPPER.CUSTOMERID(+)  AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+)");


	}
	else if (hblAttributes.getInvokerOperation().equals("HBLChargesOriginView"))
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@-- entered :"+hblAttributes.getInvokerOperation()); 

//OLD QUERY
//SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE  ORIGINTERMINAL='DHLHKG'   AND ROUND(TO_DATE('23/03/2005 13:03','DD/MM/YYYY HH24:MI') -HOUSEDOCDATE ) < 15  AND SHIPMENTMODE =2 AND HOUSEDOCID LIKE '%' UNION 	SELECT CONSOLEID FROM FS_FRS_CONSOLEMASTER  WHERE 	DIRECTCONSOLE='Y' AND   ORIGINSTATUS IS NULL  AND ROUND(TO_DATE('23/03/2005 13:03','DD/MM/YYYY HH24:MI') -CONSOLEDATE ) < 15   AND CONSOLEID LIKE '%' AND ORIGINTERMINAL='DHLHKG';

//ADVANCED QUERY
/*SELECT 

 A.HOUSEDOCID ,

 HD.ORIGINTERMINAL ,

 HD.DESTTERMINAL ,

 HD.GROSSWEIGHT,

 HD.TOTPIECES,

 HD.ACTUALVOLUME ,

 SHIPPER.CUSTOMERID SHIPPERID  , 

 SHIPPER.COMPANYNAME SHIPPERNAME ,

 CONSIGNEE.CUSTOMERID CONSIGNEEID , 

 CONSIGNEE.COMPANYNAME  CONSIGNEENAME

FROM 

(
SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR 
WHERE ORIGINTERMINAL='"+hblAttributes.getTerminalID()+"'  
AND SHIPMENTMODE =2 AND HOUSEDOCID LIKE '%' UNION 	
SELECT CONSOLEID FROM FS_FRS_CONSOLEMASTER  WHERE 	DIRECTCONSOLE='Y' AND   
ORIGINSTATUS IS NULL  AND ORIGINTERMINAL='"+hblAttributes.getTerminalID()+"'
) A, FS_FR_HOUSEDOCHDR HD,

 FS_FR_CUSTOMERMASTER SHIPPER,

  FS_FR_CUSTOMERMASTER CONSIGNEE 

WHERE 

 A.HOUSEDOCID = HD.HOUSEDOCID(+)

AND HD.SHIPPERID = SHIPPER.CUSTOMERID(+) 

  AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+);*/

selectClause.append("SELECT A.HOUSEDOCID , HD.ORIGINTERMINAL , HD.DESTTERMINAL , HD.GROSSWEIGHT, HD.TOTPIECES, HD.ACTUALVOLUME ,");     
selectClause.append(" SHIPPER.CUSTOMERID SHIPPERID  , SHIPPER.COMPANYNAME SHIPPERNAME , CONSIGNEE.CUSTOMERID CONSIGNEEID , ");           
selectClause.append(" CONSIGNEE.COMPANYNAME  CONSIGNEENAME   ");

fromClause.append(" FROM ( SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE ORIGINTERMINAL='");
fromClause.append(hblAttributes.getTerminalID());
fromClause.append("' ");
fromClause.append(" AND SHIPMENTMODE =2 AND HOUSEDOCID LIKE '%' UNION SELECT CONSOLEID FROM FS_FRS_CONSOLEMASTER  WHERE ");	fromClause.append(" DIRECTCONSOLE='Y' AND   ORIGINSTATUS IS NULL  AND ORIGINTERMINAL='");
fromClause.append(hblAttributes.getTerminalID());
fromClause.append("' ");
fromClause.append(" ) A, FS_FR_HOUSEDOCHDR HD, FS_FR_CUSTOMERMASTER SHIPPER,  FS_FR_CUSTOMERMASTER CONSIGNEE ");

whereClause.append(" WHERE  A.HOUSEDOCID = HD.HOUSEDOCID(+) AND HD.SHIPPERID = SHIPPER.CUSTOMERID(+)  AND ");
whereClause.append(" HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+)");

	}

else if (hblAttributes.getInvokerOperation().equals("HBLSuppliChargesOriginAdd") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@-- entered :"+hblAttributes.getInvokerOperation()); 

//OLD QUERY
//SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE (ORIGINSTATUS ='F' OR DESTINATIONSTATUS='F')  AND SHIPMENTMODE = 2 AND ORIGINTERMINAL ='DHLHKG'  UNION  SELECT CONSOLEID FROM FS_FRS_CONSOLEMASTER  WHERE DIRECTCONSOLE='Y'   AND (ORIGINSTATUS = 'F' OR DESTINATIONSTATUS='F') AND ORIGINTERMINAL ='DHLHKG' ;

//ADVANCED QUERY
/*SELECT 

 A.HOUSEDOCID ,

 HD.ORIGINTERMINAL ,

 HD.DESTTERMINAL ,

 HD.GROSSWEIGHT,

 HD.TOTPIECES,

 HD.ACTUALVOLUME ,

 SHIPPER.CUSTOMERID SHIPPERID  , 

 SHIPPER.COMPANYNAME SHIPPERNAME ,

 CONSIGNEE.CUSTOMERID CONSIGNEEID , 

 CONSIGNEE.COMPANYNAME  CONSIGNEENAME

FROM 

(
SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR  
WHERE (ORIGINSTATUS ='F' OR DESTINATIONSTATUS='F')  AND SHIPMENTMODE = 2 
AND ORIGINTERMINAL ='"+hblAttributes.getTerminalID()+"'  UNION  SELECT CONSOLEID FROM FS_FRS_CONSOLEMASTER  
WHERE DIRECTCONSOLE='Y'   AND (ORIGINSTATUS = 'F' OR DESTINATIONSTATUS='F') 
AND ORIGINTERMINAL ='"+hblAttributes.getTerminalID()+"' 
) A, FS_FR_HOUSEDOCHDR HD,

 FS_FR_CUSTOMERMASTER SHIPPER,

  FS_FR_CUSTOMERMASTER CONSIGNEE 

WHERE 

 A.HOUSEDOCID = HD.HOUSEDOCID(+)

AND HD.SHIPPERID = SHIPPER.CUSTOMERID(+) 

  AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+);*/

selectClause.append("SELECT  A.HOUSEDOCID, HD.ORIGINTERMINAL , HD.DESTTERMINAL , HD.GROSSWEIGHT, HD.TOTPIECES,");
selectClause.append(" HD.ACTUALVOLUME , SHIPPER.CUSTOMERID SHIPPERID  ,  SHIPPER.COMPANYNAME SHIPPERNAME ,");
selectClause.append(" CONSIGNEE.CUSTOMERID CONSIGNEEID ,  CONSIGNEE.COMPANYNAME  CONSIGNEENAME");

fromClause.append(" FROM ( SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR  WHERE (ORIGINSTATUS ='F' OR DESTINATIONSTATUS='F') ");
fromClause.append(" AND SHIPMENTMODE = 2 AND ORIGINTERMINAL ='");
fromClause.append(hblAttributes.getTerminalID());
fromClause.append("' ");
fromClause.append(" UNION  SELECT CONSOLEID FROM FS_FRS_CONSOLEMASTER  WHERE DIRECTCONSOLE='Y'   AND (ORIGINSTATUS = 'F' ");
fromClause.append(" OR DESTINATIONSTATUS='F') AND ORIGINTERMINAL ='");
fromClause.append(hblAttributes.getTerminalID());
fromClause.append("' ");
fromClause.append(") A ");

fromClause.append(" , FS_FR_HOUSEDOCHDR HD, FS_FR_CUSTOMERMASTER SHIPPER,  FS_FR_CUSTOMERMASTER CONSIGNEE ");

whereClause.append(" WHERE  A.HOUSEDOCID = HD.HOUSEDOCID(+) AND HD.SHIPPERID = SHIPPER.CUSTOMERID(+) ");
whereClause.append(" AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+) ");

	}

else if (hblAttributes.getInvokerOperation().equals("HBLChargesDestAdd")||hblAttributes.getInvokerOperation().equals("HBLChargesDestModify")||hblAttributes.getInvokerOperation().equals("HBLChargesDestView")||hblAttributes.getInvokerOperation().equals("HBLChargesDestDelete") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@-- entered :"+hblAttributes.getInvokerOperation()); 

//OLD QUERY
//SELECT RP.HAWB_ID, RP.PRMY_MODE FROM FS_RT_PLAN RP, FS_FR_HOUSEDOCHDR HD WHERE HD.SHIPMENTMODE=2 AND RP.HAWB_ID = HD.HOUSEDOCID AND HD.HOUSEDOCID NOT IN ( SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE DESTINATIONSTATUS = 'F'  AND ORIGINSTATUS = 'F' ) AND RP.HAWB_ID IN ( SELECT A.HAWB_ID FROM FS_RT_PLAN A, FS_RT_LEG B WHERE A.RT_PLAN_ID = B.RT_PLAN_ID  AND ROUND( TO_DATE('23/03/2005 13:03', 'DD/MM/YYYY HH24:MI') - B.RECEIVED_DATE) < 15 AND A.DEST_TRML_ID = 'DHLHKG'  AND ((B.LEG_TYPE IN ('TP','GT','TG') AND B.SHPMNT_STATUS IN ('P','B')) OR (B.LEG_TYPE ='GT' AND B.AUTO_MNUL_FLAG='M')) AND ( (B.SHPMNT_MODE = 2 AND RP.PRMY_MODE != 2) OR (RP.PRMY_MODE = 2) ) )  AND RP.HAWB_ID LIKE '%'  UNION SELECT RP.HAWB_ID, RP.PRMY_MODE FROM FS_RT_PLAN RP, FS_FR_HOUSEDOCHDR HD WHERE RP.HAWB_ID = HD.HOUSEDOCID AND HD.HOUSEDOCID NOT IN ( SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE DESTINATIONSTATUS = 'F'  AND ORIGINSTATUS = 'F' ) AND RP.HAWB_ID IN ( SELECT A.HAWB_ID FROM FS_RT_PLAN A, FS_RT_LEG B WHERE A.RT_PLAN_ID = B.RT_PLAN_ID  AND ROUND( TO_DATE('23/03/2005 13:03', 'DD/MM/YYYY HH24:MI') - B.RECEIVED_DATE) < 15 AND A.DEST_TRML_ID = 'DHLHKG'  AND ((B.LEG_TYPE IN ('TP','GT','TG') AND B.SHPMNT_STATUS IN ('P','B')) OR (B.LEG_TYPE ='GT' AND B.AUTO_MNUL_FLAG='M'))  AND ( (B.SHPMNT_MODE = 2 AND RP.PRMY_MODE != 2) OR (RP.PRMY_MODE = 2) ) )  AND RP.HAWB_ID LIKE '%' ;

//ADVANCED QUERY
/*SELECT 

 A.HAWB_ID,

 HD.ORIGINTERMINAL ,

 HD.DESTTERMINAL ,

 HD.GROSSWEIGHT,

 HD.TOTPIECES,

 HD.ACTUALVOLUME ,

 SHIPPER.CUSTOMERID SHIPPERID  , 

 SHIPPER.COMPANYNAME SHIPPERNAME ,

 CONSIGNEE.CUSTOMERID CONSIGNEEID , 

 CONSIGNEE.COMPANYNAME  CONSIGNEENAME

FROM 

(
SELECT RP.HAWB_ID, RP.PRMY_MODE FROM FS_RT_PLAN RP, FS_FR_HOUSEDOCHDR HD WHERE HD.SHIPMENTMODE=2 
AND RP.HAWB_ID = HD.HOUSEDOCID AND HD.HOUSEDOCID NOT IN 
( SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE DESTINATIONSTATUS = 'F'  AND ORIGINSTATUS = 'F' ) 
AND RP.HAWB_ID IN ( SELECT A.HAWB_ID FROM FS_RT_PLAN A, FS_RT_LEG B WHERE A.RT_PLAN_ID = B.RT_PLAN_ID  
AND A.DEST_TRML_ID = '"+hblAttributes.getTerminalID()+"'  
AND ((B.LEG_TYPE IN ('TP','GT','TG') AND B.SHPMNT_STATUS IN ('P','B')) OR (B.LEG_TYPE ='GT' AND B.AUTO_MNUL_FLAG='M')) 
AND ( (B.SHPMNT_MODE = 2 AND RP.PRMY_MODE != 2) OR (RP.PRMY_MODE = 2) ) )  
UNION SELECT RP.HAWB_ID, RP.PRMY_MODE FROM FS_RT_PLAN RP, FS_FR_HOUSEDOCHDR HD WHERE RP.HAWB_ID = HD.HOUSEDOCID 
AND HD.HOUSEDOCID NOT IN ( SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE DESTINATIONSTATUS = 'F'  AND ORIGINSTATUS = 'F' ) 
AND RP.HAWB_ID IN ( SELECT A.HAWB_ID FROM FS_RT_PLAN A, FS_RT_LEG B WHERE A.RT_PLAN_ID = B.RT_PLAN_ID  
AND A.DEST_TRML_ID = '"+hblAttributes.getTerminalID()+"'  
AND ((B.LEG_TYPE IN ('TP','GT','TG') AND B.SHPMNT_STATUS IN ('P','B')) OR (B.LEG_TYPE ='GT' AND B.AUTO_MNUL_FLAG='M'))  
AND ( (B.SHPMNT_MODE = 2 AND RP.PRMY_MODE != 2) OR (RP.PRMY_MODE = 2) ) )  

) A, FS_FR_HOUSEDOCHDR HD,

 FS_FR_CUSTOMERMASTER SHIPPER,

  FS_FR_CUSTOMERMASTER CONSIGNEE 

WHERE 

 A.HAWB_ID = HD.HOUSEDOCID(+)

AND HD.SHIPPERID = SHIPPER.CUSTOMERID(+) 

  AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+);*/

  selectClause.append("SELECT  A.HAWB_ID, HD.ORIGINTERMINAL , HD.DESTTERMINAL , HD.GROSSWEIGHT, HD.TOTPIECES, HD.ACTUALVOLUME , ");
selectClause.append(" SHIPPER.CUSTOMERID SHIPPERID  ,  SHIPPER.COMPANYNAME SHIPPERNAME , CONSIGNEE.CUSTOMERID CONSIGNEEID ,");  selectClause.append(" CONSIGNEE.COMPANYNAME  CONSIGNEENAME ");

fromClause.append(" FROM ( SELECT RP.HAWB_ID, RP.PRMY_MODE FROM FS_RT_PLAN RP, FS_FR_HOUSEDOCHDR HD WHERE HD.SHIPMENTMODE=2 ");
fromClause.append(" AND RP.HAWB_ID = HD.HOUSEDOCID AND HD.HOUSEDOCID NOT IN ");
fromClause.append(" ( SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE DESTINATIONSTATUS = 'F'  AND ORIGINSTATUS = 'F' ) ");
fromClause.append(" AND RP.HAWB_ID IN ( SELECT A.HAWB_ID FROM FS_RT_PLAN A, FS_RT_LEG B WHERE A.RT_PLAN_ID = B.RT_PLAN_ID "); 
fromClause.append(" AND A.DEST_TRML_ID = '");
fromClause.append(hblAttributes.getTerminalID());
fromClause.append("' ");
fromClause.append(" AND ((B.LEG_TYPE IN ('TP','GT','TG') AND B.SHPMNT_STATUS IN ('P','B')) OR (B.LEG_TYPE ='GT' ");
fromClause.append(" AND B.AUTO_MNUL_FLAG='M'))"); 
fromClause.append(" AND ( (B.SHPMNT_MODE = 2 AND RP.PRMY_MODE != 2) OR (RP.PRMY_MODE = 2) ) )  ");
fromClause.append(" UNION SELECT RP.HAWB_ID, RP.PRMY_MODE FROM FS_RT_PLAN RP, FS_FR_HOUSEDOCHDR HD WHERE RP.HAWB_ID = HD.HOUSEDOCID ");
fromClause.append(" AND HD.HOUSEDOCID NOT IN ( SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE DESTINATIONSTATUS = 'F' ");
fromClause.append(" AND ORIGINSTATUS = 'F' ) ");
fromClause.append( "AND RP.HAWB_ID IN ( SELECT A.HAWB_ID FROM FS_RT_PLAN A, FS_RT_LEG B WHERE A.RT_PLAN_ID = B.RT_PLAN_ID  ");
fromClause.append(" AND A.DEST_TRML_ID = '");
fromClause.append(hblAttributes.getTerminalID());
fromClause.append("' ");
fromClause.append(" AND ((B.LEG_TYPE IN ('TP','GT','TG') AND B.SHPMNT_STATUS IN ('P','B')) OR (B.LEG_TYPE ='GT' ");
fromClause.append(" AND B.AUTO_MNUL_FLAG='M')) ");
fromClause.append(" AND ( (B.SHPMNT_MODE = 2 AND RP.PRMY_MODE != 2) OR (RP.PRMY_MODE = 2) ) ) ) A ");

fromClause.append(" , FS_FR_HOUSEDOCHDR HD, FS_FR_CUSTOMERMASTER SHIPPER,  FS_FR_CUSTOMERMASTER CONSIGNEE ");

whereClause.append(" WHERE  A.HAWB_ID = HD.HOUSEDOCID(+) AND HD.SHIPPERID = SHIPPER.CUSTOMERID(+) AND ");
whereClause.append(" HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+) ");

	}
else if (hblAttributes.getInvokerOperation().equals("HBLSuppliChargesDestAdd") )
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@-- entered :"+hblAttributes.getInvokerOperation()); 

//OLD QUERY
//SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR  WHERE (ORIGINSTATUS ='F' OR DESTINATIONSTATUS='F')  AND SHIPMENTMODE = 2 AND DESTTERMINAL ='DHLHKG'  UNION  SELECT CONSOLEID FROM FS_FRS_CONSOLEMASTER  WHERE DIRECTCONSOLE='Y'   AND (ORIGINSTATUS = 'F' OR DESTINATIONSTATUS='F') AND DESTTERMINAL ='DHLHKG' ;
//ADVANCED QUERY
/*SELECT 

 A.HOUSEDOCID ,

 HD.ORIGINTERMINAL ,

 HD.DESTTERMINAL ,

 HD.GROSSWEIGHT,

 HD.TOTPIECES,

 HD.ACTUALVOLUME ,

 SHIPPER.CUSTOMERID SHIPPERID  , 

 SHIPPER.COMPANYNAME SHIPPERNAME ,

 CONSIGNEE.CUSTOMERID CONSIGNEEID , 

 CONSIGNEE.COMPANYNAME  CONSIGNEENAME

FROM 

(
SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR  
WHERE (ORIGINSTATUS ='F' OR DESTINATIONSTATUS='F')  AND SHIPMENTMODE = 2 AND DESTTERMINAL ='"+hblAttributes.getTerminalID()+"'  
UNION  SELECT CONSOLEID FROM FS_FRS_CONSOLEMASTER  WHERE DIRECTCONSOLE='Y'   
AND (ORIGINSTATUS = 'F' OR DESTINATIONSTATUS='F') AND DESTTERMINAL ='"+hblAttributes.getTerminalID()+"'  

) A, FS_FR_HOUSEDOCHDR HD,

 FS_FR_CUSTOMERMASTER SHIPPER,

  FS_FR_CUSTOMERMASTER CONSIGNEE 

WHERE 

 A.HOUSEDOCID = HD.HOUSEDOCID(+)

AND HD.SHIPPERID = SHIPPER.CUSTOMERID(+) 

  AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+);*/
//GS
selectClause.append(" SELECT  A.HOUSEDOCID, HD.ORIGINTERMINAL , HD.DESTTERMINAL , HD.GROSSWEIGHT, HD.TOTPIECES, ");
selectClause.append(" HD.ACTUALVOLUME , SHIPPER.CUSTOMERID SHIPPERID  ,  SHIPPER.COMPANYNAME SHIPPERNAME , ");
selectClause.append(" CONSIGNEE.CUSTOMERID CONSIGNEEID ,  CONSIGNEE.COMPANYNAME  CONSIGNEENAME ");

fromClause.append(" FROM ( SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR  WHERE (ORIGINSTATUS ='F' OR DESTINATIONSTATUS='F') ");
fromClause.append(" AND SHIPMENTMODE = 2 AND ORIGINTERMINAL ='");
fromClause.append(hblAttributes.getTerminalID());
fromClause.append("' ");
fromClause.append(" UNION  SELECT CONSOLEID FROM FS_FRS_CONSOLEMASTER  WHERE DIRECTCONSOLE='Y'  ");
fromClause.append(" AND (ORIGINSTATUS = 'F' OR DESTINATIONSTATUS='F') AND DESTTERMINAL  ='");
fromClause.append(hblAttributes.getTerminalID());
fromClause.append("' ");
fromClause.append(") A ");

fromClause.append(" , FS_FR_HOUSEDOCHDR HD, FS_FR_CUSTOMERMASTER SHIPPER,  FS_FR_CUSTOMERMASTER CONSIGNEE ");

whereClause.append(" WHERE  A.HOUSEDOCID = HD.HOUSEDOCID(+) AND HD.SHIPPERID = SHIPPER.CUSTOMERID(+) ");
whereClause.append(" AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+) ");

	}

else if (hblAttributes.getInvokerOperation().equals("HBLDestAttach"))
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@-- entered :"+hblAttributes.getInvokerOperation()); 

//OLD QUERY
//SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE SHIPMENTMODE=2 AND HOUSEDOCID LIKE '%' AND  DESTTERMINAL ='DHLHKG' 
//ADVANCED QUERY
/*SELECT	HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID CONSIGNEEID
,CONSIGNEE.COMPANYNAME CONSIGNEENAME,ORIGINTERMINAL,DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES ,HD.ACTUALVOLUME
FROM  FS_FR_HOUSEDOCHDR HD, FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE 
WHERE SHIPPER.CUSTOMERID(+) = SHIPPERID AND CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID 
AND SHIPMENTMODE=2  AND  DESTTERMINAL ='DHLHKG' ;*/
selectClause.append(" SELECT	HD.HOUSEDOCID,SHIPPER.CUSTOMERID SHIPPERID,SHIPPER.COMPANYNAME SHIPPERNAME,");
selectClause.append(" CONSIGNEE.CUSTOMERID CONSIGNEEID,CONSIGNEE.COMPANYNAME CONSIGNEENAME,ORIGINTERMINAL,");
selectClause.append(" DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES ,HD.ACTUALVOLUME ");


fromClause.append(" FROM  FS_FR_HOUSEDOCHDR HD, FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE ");

whereClause.append(" WHERE SHIPPER.CUSTOMERID(+) = SHIPPERID AND CONSIGNEE.CUSTOMERID(+) = CONSIGNEEID ");
whereClause.append(" AND SHIPMENTMODE=2  ");
whereClause.append(" AND  DESTTERMINAL ='");
whereClause.append(hblAttributes.getTerminalID());
whereClause.append("' ");


	}
else if (hblAttributes.getInvokerOperation().equals("AESSED"))
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@@@-- entered :"+hblAttributes.getInvokerOperation()); 

//OLD QUERY
//SELECT CONSOLEID  FROM FS_FRS_CONSOLEMASTER WHERE DIRECTCONSOLE='Y' AND CONSOLEID LIKE '%' AND ORIGINTERMINAL =  'DHLHKG' AND CONSOLEID NOT IN(SELECT HOUSENO FROM FS_FR_SEDSHIPMENTDTL WHERE SUBMISSIONDATE IS NOT NULL)  UNION SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE SHIPMENTMODE=2 AND HOUSEDOCID LIKE '%'  AND ORIGINTERMINAL ='DHLHKG' AND HOUSEDOCID  NOT IN(SELECT HOUSENO FROM FS_FR_SEDSHIPMENTDTL WHERE SUBMISSIONDATE IS NOT NULL )|SELECT CONSOLEID  FROM FS_FRS_CONSOLEMASTER WHERE DIRECTCONSOLE='Y' AND CONSOLEID LIKE '%' AND ORIGINTERMINAL =  'DHLHKG' AND CONSOLEID NOT IN(SELECT HOUSENO FROM FS_FR_SEDSHIPMENTDTL WHERE SUBMISSIONDATE IS NOT NULL)  UNION SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE SHIPMENTMODE=2 AND HOUSEDOCID LIKE '%'  AND ORIGINTERMINAL ='DHLHKG' AND HOUSEDOCID  NOT IN(SELECT HOUSENO FROM FS_FR_SEDSHIPMENTDTL WHERE SUBMISSIONDATE IS NOT NULL );
//ADVANCED QUERY
/*SELECT	CONSOLEID,SHIPPER.CUSTOMERID SHIPPERID,SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID CONSIGNEEID
,CONSIGNEE.COMPANYNAME CONSIGNEENAME,ORIGINTERMINAL,DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES ,HD.ACTUALVOLUME
FROM (

SELECT CONSOLEID   FROM FS_FRS_CONSOLEMASTER WHERE DIRECTCONSOLE='Y'  AND ORIGINTERMINAL =  'DHLHKG' 
AND CONSOLEID NOT IN(SELECT HOUSENO FROM FS_FR_SEDSHIPMENTDTL WHERE SUBMISSIONDATE IS NOT NULL)  
UNION 
SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE SHIPMENTMODE=2   AND ORIGINTERMINAL ='DHLHKG' 
AND HOUSEDOCID  NOT IN(SELECT HOUSENO FROM FS_FR_SEDSHIPMENTDTL WHERE SUBMISSIONDATE IS NOT NULL )

) A,
FS_FR_HOUSEDOCHDR HD,

 FS_FR_CUSTOMERMASTER SHIPPER,

 FS_FR_CUSTOMERMASTER CONSIGNEE 

WHERE  

 HD.SHIPPERID = SHIPPER.CUSTOMERID(+) 

 AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+)

 AND A.CONSOLEID = HD.HOUSEDOCID(+);*/


//GS
selectClause.append(" SELECT	CONSOLEID,SHIPPER.CUSTOMERID SHIPPERID,SHIPPER.COMPANYNAME SHIPPERNAME,");
selectClause.append(" CONSIGNEE.CUSTOMERID CONSIGNEEID ,CONSIGNEE.COMPANYNAME CONSIGNEENAME,ORIGINTERMINAL,");
selectClause.append(" DESTTERMINAL,HD.GROSSWEIGHT , HD.TOTPIECES ,HD.ACTUALVOLUME ");

fromClause.append(" FROM (SELECT CONSOLEID   FROM FS_FRS_CONSOLEMASTER WHERE DIRECTCONSOLE='Y' ");
fromClause.append(" AND ORIGINTERMINAL =  '");
fromClause.append(hblAttributes.getTerminalID());
fromClause.append("' "); 
fromClause.append(" AND CONSOLEID NOT IN(SELECT HOUSENO FROM FS_FR_SEDSHIPMENTDTL WHERE SUBMISSIONDATE IS NOT NULL) "); 
fromClause.append(" UNION SELECT HOUSEDOCID FROM FS_FR_HOUSEDOCHDR WHERE SHIPMENTMODE=2   AND ORIGINTERMINAL ='");
fromClause.append(hblAttributes.getTerminalID());
fromClause.append("' ");
fromClause.append(" AND HOUSEDOCID  NOT IN(SELECT HOUSENO FROM FS_FR_SEDSHIPMENTDTL WHERE SUBMISSIONDATE ");
fromClause.append(" IS NOT NULL )) A,FS_FR_HOUSEDOCHDR HD, FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE ");

whereClause.append(" WHERE   HD.SHIPPERID = SHIPPER.CUSTOMERID(+)  AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+) ");
whereClause.append(" AND A.CONSOLEID = HD.HOUSEDOCID(+) ");

	}

else if (hblAttributes.getInvokerOperation().equals("InvoiceShipperSeaJobCost")||hblAttributes.getInvokerOperation().equals("InvoiceShipperSeaJobCostReport"))
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@@@-- entered :"+hblAttributes.getInvokerOperation()); 
//OLD QUERY
//SELECT DISTINCT H.HOUSEDOCID FROM FS_FR_HOUSEDOCHDR H,FS_FR_HOUSEDOCCHARGES C WHERE H.ORIGINTERMINAL = 'DHLMAA'  AND H.SHIPMENTMODE=2  AND C.COSTINCURREDAT='Origin' AND H.HOUSEDOCID LIKE '%' AND   C.CHARGEID NOT IN('1','2','3','4','5','6','7','8','9','10') AND H.HOUSEDOCID=C.HOUSEDOCID UNION  SELECT DISTINCT  CONSOLEID COLID FROM FS_FRS_CONSOLEMASTER,FS_FR_HOUSEDOCCHARGES C WHERE DIRECTCONSOLE='Y' AND ORIGINTERMINAL='DHLMAA' AND CONSOLEID LIKE '%'   AND CONSOLEID=C.HOUSEDOCID

//ADVANCED QUERY
/* 
SELECT HD.HOUSEDOCID  ,SHIPPER.CUSTOMERID SHIPPERID, SHIPPER.COMPANYNAME SHIPPERNAME ,CONSIGNEE.CUSTOMERID CONSIGNEEID ,  CONSIGNEE.COMPANYNAME  CONSIGNEENAME, HD.ORIGINTERMINAL , HD.DESTTERMINAL , HD.GROSSWEIGHT, HD.TOTPIECES,HD.ACTUALVOLUME   
FROM(
SELECT DISTINCT HD.HOUSEDOCID ,SHIPPER.CUSTOMERID SHIPPERID,  SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID  CONSIGNEEID, CONSIGNEE.COMPANYNAME CONSIGNEENAME, HD.ORIGINTERMINAL,HD.DESTTERMINAL,  HD.GROSSWEIGHT ,  HD.TOTPIECES ,HD.ACTUALVOLUME,HD.ORIGINLOCATION ,HD.DESTINATIONLOCATION,HD.HOUSEDOCDATE 
FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER  SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE ,
FS_FR_HOUSEDOCCHARGES C WHERE HD.ORIGINTERMINAL = 'DHLMAA' 
AND  HD.SHIPPERID =  SHIPPER.CUSTOMERID  AND  HD.CONSIGNEEID  = CONSIGNEE.CUSTOMERID  
AND HD.SHIPMENTMODE=2  AND C.COSTINCURREDAT='Origin' AND HD.HOUSEDOCID LIKE '%' AND   C.CHARGEID NOT IN('1','2','3','4','5','6','7','8','9','10') AND HD.HOUSEDOCID=C.HOUSEDOCID 
UNION  
SELECT DISTINCT  CONSOLEID ,SHIPPER.CUSTOMERID SHIPPERID,  SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID  CONSIGNEEID, CONSIGNEE.COMPANYNAME CONSIGNEENAME,ORIGINTERMINAL ,DESTTERMINAL ,WEIGHT GROSSWEIGHT,NOOFPKGS TOTPIECES,VOLUME ACTUALVOLUME,ORIGINLOCATION ,DESTLOCATION ,CONSOLEDATE  FROM
FS_FRS_CONSOLEMASTER CM,FS_FR_HOUSEDOCCHARGES C,
FS_FR_CUSTOMERMASTER  SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE  
WHERE  DIRECTCONSOLE='Y' AND ORIGINTERMINAL='DHLMAA' AND CM.SHIPPERID =  SHIPPER.CUSTOMERID  AND  CM.CONSIGNEEID  = CONSIGNEE.CUSTOMERID AND CM.CONSOLEID=C.HOUSEDOCID  
)HD,
FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE   
WHERE   HD.SHIPPERID = SHIPPER.CUSTOMERID(+) 
AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+) 
AND ROUND(SYSDATE- HD.HOUSEDOCDATE ) <= 15 ORDER BY HD.HOUSEDOCID DESC ;;

*/
selectClause.append("SELECT HD.HOUSEDOCID  ,SHIPPER.CUSTOMERID SHIPPERID, SHIPPER.COMPANYNAME SHIPPERNAME ,CONSIGNEE.CUSTOMERID CONSIGNEEID ,  CONSIGNEE.COMPANYNAME  CONSIGNEENAME, HD.ORIGINTERMINAL , HD.DESTTERMINAL , HD.GROSSWEIGHT, HD.TOTPIECES,HD.ACTUALVOLUME ");

fromClause.append(" FROM( SELECT DISTINCT HD.HOUSEDOCID ,SHIPPER.CUSTOMERID SHIPPERID,  SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID  CONSIGNEEID, CONSIGNEE.COMPANYNAME CONSIGNEENAME, HD.ORIGINTERMINAL,HD.DESTTERMINAL,  HD.GROSSWEIGHT ,  HD.TOTPIECES ,HD.ACTUALVOLUME,HD.ORIGINLOCATION ,HD.DESTINATIONLOCATION,HD.HOUSEDOCDATE FROM FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER  SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE ,FS_FR_HOUSEDOCCHARGES C WHERE HD.ORIGINTERMINAL = '"+hblAttributes.getTerminalID()+"' AND  HD.SHIPPERID =  SHIPPER.CUSTOMERID  AND  HD.CONSIGNEEID  = CONSIGNEE.CUSTOMERID AND HD.SHIPMENTMODE=2  AND C.COSTINCURREDAT='Origin' AND HD.HOUSEDOCID LIKE '%' AND   C.CHARGEID NOT  IN('1','2','3','4','5','6','7','8','9','10') AND HD.HOUSEDOCID=C.HOUSEDOCID UNION SELECT DISTINCT  CONSOLEID ,SHIPPER.CUSTOMERID SHIPPERID,  SHIPPER.COMPANYNAME SHIPPERNAME,CONSIGNEE.CUSTOMERID  CONSIGNEEID, CONSIGNEE.COMPANYNAME CONSIGNEENAME,ORIGINTERMINAL ,DESTTERMINAL ,WEIGHT GROSSWEIGHT,NOOFPKGS TOTPIECES,VOLUME ACTUALVOLUME,ORIGINLOCATION ,DESTLOCATION ,CONSOLEDATE  FROM FS_FRS_CONSOLEMASTER CM,FS_FR_HOUSEDOCCHARGES C, FS_FR_CUSTOMERMASTER  SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE WHERE  DIRECTCONSOLE='Y' AND ORIGINTERMINAL='"+hblAttributes.getTerminalID()+"' AND CM.SHIPPERID =  SHIPPER.CUSTOMERID  AND  CM.CONSIGNEEID  = CONSIGNEE.CUSTOMERID AND CM.CONSOLEID=C.HOUSEDOCID )HD, FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE ");

whereClause.append(" WHERE   HD.SHIPPERID = SHIPPER.CUSTOMERID(+) AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+)  ");

	}
else if (hblAttributes.getInvokerOperation().equals("InvoiceConsigneeSeaJobCost"))
	{
	//	Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@@@-- entered :"+hblAttributes.getInvokerOperation()); 

//OLD QUERY
//SELECT DISTINCT HD.HOUSEDOCID FROM FS_FR_HOUSEDOCHDR HD,FS_FR_HOUSEDOCCHARGES C WHERE HD.DESTTERMINAL = 'DHLMAA'  AND HD.SHIPMENTMODE=2  AND C.COSTINCURREDAT='Destination' AND HD.HOUSEDOCID LIKE '%'  AND  C.CHARGEID NOT IN('1','2','3','4','5','6','7','8','9','10') AND HD.HOUSEDOCID=C.HOUSEDOCID ORDER BY HOUSEDOCID;

//ADVANCED QUERY
/*SELECT A.HOUSEDOCID , HD.ORIGINTERMINAL , HD.DESTTERMINAL , HD.GROSSWEIGHT, HD.TOTPIECES,HD.ACTUALVOLUME , SHIPPER.CUSTOMERID SHIPPERID  , SHIPPER.COMPANYNAME SHIPPERNAME ,  CONSIGNEE.CUSTOMERID CONSIGNEEID ,  CONSIGNEE.COMPANYNAME  CONSIGNEENAME FROM(
SELECT DISTINCT HD.HOUSEDOCID FROM FS_FR_HOUSEDOCHDR HD,FS_FR_HOUSEDOCCHARGES C WHERE HD.DESTTERMINAL = 'DHLHKG'  AND HD.SHIPMENTMODE=2  AND C.COSTINCURREDAT='Destination' AND HD.HOUSEDOCID LIKE '%'  AND  C.CHARGEID NOT IN('1','2','3','4','5','6','7','8','9','10') AND HD.HOUSEDOCID=C.HOUSEDOCID ORDER BY HOUSEDOCID
)A,
FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE WHERE  A.HOUSEDOCID = HD.HOUSEDOCID(+) AND HD.SHIPPERID = SHIPPER.CUSTOMERID(+) AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+);
*/


selectClause.append(" SELECT A.HOUSEDOCID ,SHIPPER.CUSTOMERID SHIPPERID, SHIPPER.COMPANYNAME SHIPPERNAME ,CONSIGNEE.CUSTOMERID CONSIGNEEID ,  CONSIGNEE.COMPANYNAME  CONSIGNEENAME, HD.ORIGINTERMINAL , HD.DESTTERMINAL , HD.GROSSWEIGHT, HD.TOTPIECES,HD.ACTUALVOLUME ");

fromClause.append(" FROM(SELECT DISTINCT HD.HOUSEDOCID FROM FS_FR_HOUSEDOCHDR HD,FS_FR_HOUSEDOCCHARGES C WHERE HD.DESTTERMINAL = '"+hblAttributes.getTerminalID()+"'  AND HD.SHIPMENTMODE=2  AND C.COSTINCURREDAT='Destination' AND HD.HOUSEDOCID LIKE '%'  AND  C.CHARGEID NOT IN('1','2','3','4','5','6','7','8','9','10') AND HD.HOUSEDOCID=C.HOUSEDOCID ORDER BY HOUSEDOCID )A,FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE ");

whereClause.append(" WHERE  A.HOUSEDOCID = HD.HOUSEDOCID(+) AND HD.SHIPPERID = SHIPPER.CUSTOMERID(+) AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+) ");

	}
else if (hblAttributes.getInvokerOperation().equals("InvoiceConsigneeSeaCAN"))
	{
		//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO...@@@@@-- entered :"+hblAttributes.getInvokerOperation()); 

//OLD QUERY
//SELECT HAWB_ID FROM FS_RT_PLAN PL, FS_RT_LEG LG, FS_FR_HOUSEDOCHDR H WHERE HAWB_ID LIKE '%' AND H.HOUSEDOCID = PL.HAWB_ID AND LG.RT_PLAN_ID  = PL.RT_PLAN_ID AND LG.DEST_TRML_ID = 'DHLMAA' AND LG.SHPMNT_STATUS IN('C','P','B') AND H.SHIPMENTMODE=2
//ADVANCED QUERY
/*SELECT A.HAWB_ID ,SHIPPER.CUSTOMERID SHIPPERID, SHIPPER.COMPANYNAME SHIPPERNAME ,CONSIGNEE.CUSTOMERID CONSIGNEEID ,  CONSIGNEE.COMPANYNAME  CONSIGNEENAME, HD.ORIGINTERMINAL , HD.DESTTERMINAL , HD.GROSSWEIGHT, HD.TOTPIECES,HD.ACTUALVOLUME FROM(
SELECT HAWB_ID FROM FS_RT_PLAN PL, FS_RT_LEG LG, FS_FR_HOUSEDOCHDR H WHERE HAWB_ID LIKE '%' AND H.HOUSEDOCID = PL.HAWB_ID AND LG.RT_PLAN_ID  = PL.RT_PLAN_ID AND LG.DEST_TRML_ID = 'DHLMAA' AND LG.SHPMNT_STATUS IN('C','P','B') AND H.SHIPMENTMODE=2
)A,
 
FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE WHERE  A.HAWB_ID   = HD.HOUSEDOCID(+) AND HD.SHIPPERID = SHIPPER.CUSTOMERID(+) AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+);*/


selectClause.append(" SELECT A.HAWB_ID ,SHIPPER.CUSTOMERID SHIPPERID, SHIPPER.COMPANYNAME SHIPPERNAME ,CONSIGNEE.CUSTOMERID CONSIGNEEID ,  CONSIGNEE.COMPANYNAME  CONSIGNEENAME, HD.ORIGINTERMINAL , HD.DESTTERMINAL , HD.GROSSWEIGHT, HD.TOTPIECES,HD.ACTUALVOLUME");

fromClause.append(" FROM(SELECT HAWB_ID FROM FS_RT_PLAN PL, FS_RT_LEG LG, FS_FR_HOUSEDOCHDR H WHERE HAWB_ID LIKE '%' AND H.HOUSEDOCID = PL.HAWB_ID AND LG.RT_PLAN_ID  = PL.RT_PLAN_ID AND LG.DEST_TRML_ID = '"+hblAttributes.getTerminalID()+"' AND LG.SHPMNT_STATUS IN('C','P','B') AND H.SHIPMENTMODE=2 )A, FS_FR_HOUSEDOCHDR HD,FS_FR_CUSTOMERMASTER SHIPPER, FS_FR_CUSTOMERMASTER CONSIGNEE ");

whereClause.append(" WHERE  A.HAWB_ID   = HD.HOUSEDOCID(+) AND HD.SHIPPERID = SHIPPER.CUSTOMERID(+) AND HD.CONSIGNEEID = CONSIGNEE.CUSTOMERID(+) ");

	}











			//Logger.info(FILE_NAME,"...............ETHBLAdvDAO........HblId..........."+hblAttributes.getHblId());
			if(hblAttributes.getHblId()!=null && !hblAttributes.getHblId().equals(""))
		         { 
				    whereClause.append(" AND HD.HOUSEDOCID ");
                    whereClause.append(getSearchString(searchValues.getSearchType(),hblAttributes.getHblId().trim()));
				 }
          
			if(hblAttributes.getShipperName()!=null && !hblAttributes.getShipperName().trim().equals(""))
		         { 
				    whereClause.append(" AND SHIPPER.COMPANYNAME ");
                    whereClause.append(getSearchString(searchValues.getSearchType(),hblAttributes.getShipperName().trim()));
				 }
		
            if(hblAttributes.getConsigneeName()!=null && !hblAttributes.getConsigneeName().trim().equals(""))
		         { 
				    whereClause.append(" AND CONSIGNEE.COMPANYNAME ");
                    whereClause.append(getSearchString(searchValues.getSearchType(),hblAttributes.getConsigneeName().trim()));
				 }
            if(hblAttributes.getOriginTerminal()!=null && !hblAttributes.getOriginTerminal().trim().equals(""))
		         { 
				    whereClause.append(" AND HD.ORIGINTERMINAL ");
                    whereClause.append(getSearchString(searchValues.getSearchType(),hblAttributes.getOriginTerminal().trim()));
				 }
             if(hblAttributes.getDestinationTerminal()!=null && !hblAttributes.getDestinationTerminal().trim().equals(""))
		         { 
				    whereClause.append(" AND HD.DESTTERMINAL ");
                    whereClause.append(getSearchString(searchValues.getSearchType(),hblAttributes.getDestinationTerminal().trim()));
				 }
             if(hblAttributes.getOriginCountryId()!=null && !hblAttributes.getOriginCountryId().equals(""))
		         { 
				    fromClause.append(", FS_FR_LOCATIONMASTER ORCOUNTRY  ");
					whereClause.append(" AND ORCOUNTRY.LOCATIONID = HD.ORIGINLOCATION "); 
					whereClause.append(" AND ORCOUNTRY.COUNTRYID ");
					whereClause.append(getSearchString(searchValues.getSearchType(),hblAttributes.getOriginCountryId().trim()));
				 }
             if(hblAttributes.getDestinationCountryId()!=null && !hblAttributes.getDestinationCountryId().equals(""))
		         { 
				    fromClause.append(", FS_FR_LOCATIONMASTER DECOUNTRY  ");
					whereClause.append(" AND DECOUNTRY.LOCATIONID = HD.DESTINATIONLOCATION "); 
					whereClause.append(" AND DECOUNTRY.COUNTRYID ");
					whereClause.append(getSearchString(searchValues.getSearchType(),hblAttributes.getDestinationCountryId().trim()));
				 }
              if(hblAttributes.getConsoleType()!=null && !hblAttributes.getConsoleType().equals(""))
		         { 
			//Logger.info(FILE_NAME,"...@@@@@@@@@@.ETHBLAdvDAO....hblAttributes.getConsoleType()...."+hblAttributes.getConsoleType());     	
				    whereClause.append(" AND HD.CONSOLTYPE  "); 
					whereClause.append(getSearchString(searchValues.getSearchType(),hblAttributes.getConsoleType().trim()));
				 }
				// Logger.info(FILE_NAME,"...............ETHBLAdvDAO........searchValues.getNoOfDaysControl()..........."+searchValues.getNoOfDaysControl());
           
			if(searchValues.getNoOfDaysControl()!=null && !searchValues.getNoOfDaysControl().equals(""))
		         {
				     searchString =getDaysControl(searchValues.getNoOfDaysControl(),searchValues.getNoOfDays().trim()," HD.HOUSEDOCDATE ");
    				 whereClause.append(searchString);
		         }

	    	resultQuery.append(selectClause);
			resultQuery.append(fromClause);
			resultQuery.append(whereClause);
			resultQuery.append(" ORDER BY HD.HOUSEDOCID DESC ");



   			
           // Logger.info(FILE_NAME,"....End of conditions..@@@@@@@@@..ETHBLAdvDAO..SQL QUERY.."+resultQuery.toString());     	
			pStmt = connection.prepareStatement(resultQuery.toString());
            rs = pStmt.executeQuery();

          //  Logger.info(FILE_NAME,"...............ETHBLAdvDAO........44...........");
			while(rs.next()){
			
			//Logger.info(FILE_NAME,"...............ETHBLAdvDAO.....55..............");
			  
			  ETHBLAdvVO hblAttributesArr =new ETHBLAdvVO();
			  hblAttributesArr.setHblId(rs.getString(1));
			  hblAttributesArr.setShipperId(rs.getString(2));
			  hblAttributesArr.setShipperName(rs.getString(3));
			  hblAttributesArr.setConsigneeId(rs.getString(4));
			  hblAttributesArr.setConsigneeName(rs.getString(5));
			  hblAttributesArr.setOriginTerminal(rs.getString(6));
			  hblAttributesArr.setDestinationTerminal(rs.getString(7));
			  hblAttributesArr.setActualWeight(rs.getString(8)); 
			  hblAttributesArr.setNoOfPacks(rs.getString(9)); 
			  hblAttributesArr.setVolume(rs.getString(10)); 
				
				details.add(hblAttributesArr);
			}		
			return details;
			}
       catch(Exception e){
			e.printStackTrace();
			throw new EJBException(e.getMessage());
		}finally{
			try{
				if(rs!=null){
					rs.close();
				}
				if(pStmt!=null){
					pStmt.close();
				}
				if(connection!=null){
					connection.close();
				}
			}catch(SQLException sq){
				throw new EJBException(sq.getMessage());
			}

	}
}
  /**
   * 
   * @return 
   * @throws java.sql.SQLException
   */
private  Connection getConnection() throws SQLException
	{
		return dataSource.getConnection();
	}
  
}