--------------------------------------------------------
--  DDL for Procedure DELETE_ACCOUNTS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "DELETE_ACCOUNTS" is

V_COUNT NUMBER;


begin

 FOR I IN (SELECT  DAC.CUSTOMER_ACC FROM QMS_DELETE_ACCOUNTS DAC WHERE STATUS='N' ) LOOP

     V_COUNT :=0;

DELETE FROM QMS_QUOTE_CHARGEGROUPDTL WHERE QUOTE_ID IN (SELECT  ID FROM QMS_QUOTE_MASTER
                        WHERE CUSTOMER_ID IN (I.CUSTOMER_ACC));

DELETE FROM QMS_QUOTE_RATES WHERE QUOTE_ID IN  ( SELECT  ID FROM QMS_QUOTE_MASTER
                        WHERE CUSTOMER_ID IN (I.CUSTOMER_ACC));

DELETE FROM QMS_QUOTE_CONTACTDTL  WHERE QUOTE_ID  IN  ( SELECT  ID FROM QMS_QUOTE_MASTER
                        WHERE CUSTOMER_ID IN (I.CUSTOMER_ACC));

DELETE FROM QMS_QUOTE_NOTES   WHERE QUOTE_ID  IN  ( SELECT  ID FROM QMS_QUOTE_MASTER
                        WHERE CUSTOMER_ID IN (I.CUSTOMER_ACC));

DELETE FROM QMS_QUOTES_UPDATED  WHERE QUOTE_ID  IN  ( SELECT  ID FROM QMS_QUOTE_MASTER
                        WHERE CUSTOMER_ID IN (I.CUSTOMER_ACC));
DELETE FROM QMS_QUOTE_HF_DTL WHERE  QUOTE_ID  IN  ( SELECT  ID FROM QMS_QUOTE_MASTER
                        WHERE CUSTOMER_ID IN (I.CUSTOMER_ACC));
DELETE FROM QMS_QUOTE_ATTACHMENTDTL QA WHERE QA.QUOTE_ID IN ( SELECT  ID FROM QMS_QUOTE_MASTER
                        WHERE CUSTOMER_ID IN (I.CUSTOMER_ACC));
DELETE FROM QMS_QUOTE_SPOTRATES WHERE QUOTE_ID  IN  ( SELECT  ID FROM QMS_QUOTE_MASTER
                        WHERE CUSTOMER_ID IN (I.CUSTOMER_ACC));
 COMMIT;
--DELETE FROM QMS_QUOTE_MASTER WHERE QUOTE_ID = J.QUOTE_ID ;--IN(SELECT QUOTE_ID FROM QMS_QUOTE_MASTER WHERE CUSTOMER_ID IN (I.CUSTOMER_ACC));
DELETE FROM QMS_QUOTE_MASTER WHERE CUSTOMER_ID =I.CUSTOMER_ACC;
DELETE FROM QMS_CUST_CONTACTDTL WHERE CUSTOMERID IN(I.CUSTOMER_ACC);

DELETE FROM FS_RT_LEG WHERE RT_PLAN_ID IN(SELECT RT_PLAN_ID FROM FS_RT_PLAN WHERE QUOTE_ID IN(SELECT QUOTE_ID FROM FS_RT_PLAN WHERE QUOTE_ID in (SELECT  distinct QUOTE_ID FROM QMS_QUOTE_MASTER
                        WHERE CUSTOMER_ID IN (I.CUSTOMER_ACC))));-- (SELECT QUOTE_ID FROM QMS_QUOTE_MASTER WHERE CUSTOMER_ID IN(I.CUSTOMER_ACC)));

DELETE FROM FS_RT_PLAN WHERE QUOTE_ID  in (SELECT  distinct QUOTE_ID FROM QMS_QUOTE_MASTER
                        WHERE CUSTOMER_ID IN (I.CUSTOMER_ACC)) ;--IN(SELECT QUOTE_ID FROM FS_RT_PLAN WHERE QUOTE_ID IN(SELECT QUOTE_ID FROM QMS_QUOTE_MASTER WHERE CUSTOMER_ID IN(I.CUSTOMER_ACC)))
 COMMIT;
BEGIN

DELETE FROM FS_FR_CUSTOMER_ADDRESS CA WHERE CA.CUSTOMERID IN(I.CUSTOMER_ACC);

EXCEPTION WHEN OTHERS THEN
  Dbms_Output.put_line(SQLERRM);
  Dbms_Output.put_line('EXCEPTION IN DELETING FS_FR_CUSTOMER_ADDRESS');
END;

BEGIN

DELETE FROM FS_FR_CUSTOMERMASTER CM WHERE CM.CUSTOMERID IN(I.CUSTOMER_ACC);
  V_COUNT :=1;
EXCEPTION WHEN OTHERS THEN
  V_COUNT :=0;
  Dbms_Output.put_line(SQLERRM);
  Dbms_Output.put_line('EXCEPTION IN DELETING FS_FR_CUSTOMERMASTER'||I.CUSTOMER_ACC);
END;
IF  V_COUNT>0 THEN

BEGIN

DELETE FROM FS_ADDRESS WHERE ADDRESSID IN(
SELECT CUSTOMER_ADDRESSID FROM QMS_QUOTE_MASTER QM WHERE QM.CUSTOMER_ID IN(I.CUSTOMER_ACC) GROUP BY (CUSTOMER_ADDRESSID));

UPDATE QMS_DELETE_ACCOUNTS  DAC SET DAC.STATUS ='Y' ,dac.Delete_Date = SYSDATE WHERE DAC.CUSTOMER_ACC = I.CUSTOMER_ACC;

COMMIT;

EXCEPTION WHEN OTHERS THEN
ROLLBACK;
  Dbms_Output.put_line(SQLERRM);
  Dbms_Output.put_line('EXCEPTION IN DELETING FS_ADDRESS');
END;

End If;

END LOOP;--J LOOP END

--I LOOP END



end Delete_Accounts;

/

/
