--------------------------------------------------------
--  File created - Tuesday-May-20-2014   
--------------------------------------------------------
@C:\Documents and Settings\anushav\DATEDIFF.sql
@C:\Documents and Settings\anushav\DAYS_CAL_FUN.sql
@C:\Documents and Settings\anushav\GETFREIGHTRATE.sql
@C:\Documents and Settings\anushav\GET_FREIGHT_RATE_DENSITY.sql
@C:\Documents and Settings\anushav\GET_FREIGHT_RATE_VALIDITY.sql
@C:\Documents and Settings\anushav\IS_NUMBER.sql
@C:\Documents and Settings\anushav\DBMS_SHARED_POOL.sql
@C:\Documents and Settings\anushav\PKG_QMS.sql
@C:\Documents and Settings\anushav\PKG_QMS_BUYRATES.sql
@C:\Documents and Settings\anushav\PKG_QMS_CARTAGE_ACC.sql
@C:\Documents and Settings\anushav\PKG_QMS_CHARGES.sql
@C:\Documents and Settings\anushav\QMS_ADVLOV_PKG.sql
@C:\Documents and Settings\anushav\QMS_BUY_RATES_PKG.sql
@C:\Documents and Settings\anushav\QMS_BUY_RATES_UPLOAD_PKG.sql
@C:\Documents and Settings\anushav\QMS_QUOTEPACK_NEW.sql
@C:\Documents and Settings\anushav\QMS_QUOTE_PACK.sql
@C:\Documents and Settings\anushav\QMS_QUOTE_PACK_2.sql
@C:\Documents and Settings\anushav\QMS_RATES_EXCEL.sql
@C:\Documents and Settings\anushav\QMS_REPORT_PKG.sql
@C:\Documents and Settings\anushav\QMS_RSR_RATES_PKG.sql
@C:\Documents and Settings\anushav\QMS_RSR_RATES_PKG_ACCEPTANCE.sql
@C:\Documents and Settings\anushav\QMS_SETUPS.sql
@C:\Documents and Settings\anushav\UOM_UTILS.sql
@C:\Documents and Settings\anushav\DBMS_SHARED_POOL_1.sql
@C:\Documents and Settings\anushav\PKG_QMS_1.sql
@C:\Documents and Settings\anushav\PKG_QMS_BUYRATES_1.sql
@C:\Documents and Settings\anushav\PKG_QMS_CARTAGE_ACC_1.sql
@C:\Documents and Settings\anushav\PKG_QMS_CHARGES_1.sql
@C:\Documents and Settings\anushav\QMS_ADVLOV_PKG_1.sql
@C:\Documents and Settings\anushav\QMS_BUY_RATES_PKG_1.sql
@C:\Documents and Settings\anushav\QMS_BUY_RATES_UPLOAD_PKG_1.sql
@C:\Documents and Settings\anushav\QMS_QUOTEPACK_NEW_1.sql
@C:\Documents and Settings\anushav\QMS_QUOTE_PACK_1.sql
@C:\Documents and Settings\anushav\QMS_QUOTE_PACK_2_1.sql
@C:\Documents and Settings\anushav\QMS_RATES_EXCEL_1.sql
@C:\Documents and Settings\anushav\QMS_REPORT_PKG_1.sql
@C:\Documents and Settings\anushav\QMS_RSR_RATES_PKG_1.sql
@C:\Documents and Settings\anushav\QMS_RSR_RATES_PKG_ACCEPTANCE_1.sql
@C:\Documents and Settings\anushav\QMS_SETUPS_1.sql
@C:\Documents and Settings\anushav\SELL_RATES_PROC.sql
@C:\Documents and Settings\anushav\UOM_UTILS_1.sql
@C:\Documents and Settings\anushav\ACTIVITYTEST.sql
@C:\Documents and Settings\anushav\BRRSRDELETION.sql
@C:\Documents and Settings\anushav\BUYRATEDELETE.sql
@C:\Documents and Settings\anushav\CARTAGE_UPDATION.sql
@C:\Documents and Settings\anushav\CHANGEQUOTEID.sql
@C:\Documents and Settings\anushav\CHANGEQUOTEID1.sql
@C:\Documents and Settings\anushav\CHANGEQUOTEID2.sql
@C:\Documents and Settings\anushav\CHANGEQUOTEID3.sql
@C:\Documents and Settings\anushav\CHANGEQUOTEID4.sql
@C:\Documents and Settings\anushav\COUNTRY_UPDATION.sql
@C:\Documents and Settings\anushav\CURRENCY_ARCHIVAL.sql
@C:\Documents and Settings\anushav\DBCLEARENCE.sql
@C:\Documents and Settings\anushav\DELETE_ACCOUNTS.sql
@C:\Documents and Settings\anushav\DELETE_INACTIVE_DATA.sql
@C:\Documents and Settings\anushav\DUPLICATEBRS.sql
@C:\Documents and Settings\anushav\GETMULTIQUOTEMASTERDATA.sql
@C:\Documents and Settings\anushav\GET_RATES_HEADER_PROC.sql
@C:\Documents and Settings\anushav\HTML_EMAIL.sql
@C:\Documents and Settings\anushav\INSERT_DATA.sql
@C:\Documents and Settings\anushav\NZDBCLEARENCE.sql
@C:\Documents and Settings\anushav\NZLCLDELETE_INUPDATE.sql
@C:\Documents and Settings\anushav\NZLCLDELETE_NOTUPDATE.sql
@C:\Documents and Settings\anushav\NZLCLDELETE_UPDATEDELETE.sql
@C:\Documents and Settings\anushav\NZLCLDELETE_UPDATEDELETE1.sql
@C:\Documents and Settings\anushav\PRINT_OUT.sql
@C:\Documents and Settings\anushav\QUOTES_ARCHIVE.sql
@C:\Documents and Settings\anushav\QUOTE_ESCALATION_JOBPROC.sql
@C:\Documents and Settings\anushav\REJ_GEN_APP_AU_NZ_DEL_PRC.sql
@C:\Documents and Settings\anushav\SEND_HTML_MAIL_ESC.sql
@C:\Documents and Settings\anushav\TRUNCATE_PROC.sql
