--------------------------------------------------------
--  DDL for Package Body PKG_QMS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "PKG_QMS" AS

  /*Get Terminals In Hierarchy*/
	FUNCTION GETLOCATIONSINHIERARCHY(PTERMINAL VARCHAR2, SEARCHSTR VARCHAR2) RETURN CSCOLUMNS
	IS
    TERMINALSTRING	VARCHAR2(1000):='';
    CSWB CSCOLUMNS ;
 BEGIN
    OPEN CSWB FOR  SELECT LM.LOCATIONID,LM.LOCATIONNAME,LM.SHIPMENTMODE
                  FROM FS_FR_TERMINALLOCATION TL,FS_FR_LOCATIONMASTER LM
                  WHERE TL.TERMINALID IN
                   (
                      SELECT PTERMINAL  TERM_ID   FROM DUAL
                      UNION
                      SELECT CHILD_TERMINAL_ID TERM_ID
                      FROM FS_FR_TERMINAL_REGN
                      CONNECT BY PRIOR CHILD_TERMINAL_ID=PARENT_TERMINAL_ID
                      START WITH PARENT_TERMINAL_ID = PTERMINAL
                    )
                  AND LM.LOCATIONID=TL.LOCATIONID ;
		RETURN CSWB;
	END GETLOCATIONSINHIERARCHY;

	/*** End ***/

  PROCEDURE GETLOCATIONS(PTERMINAL VARCHAR2, SEARCHSTR VARCHAR2, CSLIST OUT Pkg_Qms.CSCOLUMNS )
  AS
  BEGIN
    SELECT Pkg_Qms.GETLOCATIONSINHIERARCHY(PTERMINAL,SEARCHSTR) INTO CSLIST FROM DUAL;
  END GETLOCATIONS;


END;

/

/
