--------------------------------------------------------
--  DDL for Package QMS_QUOTE_PACK
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "QMS_QUOTE_PACK" AS

      TYPE RESULTSET IS REF CURSOR;

      G_ERR VARCHAR2(100);

      G_ERR_CODE VARCHAR2(100);
       PROCEDURE MultiLane_Buryates_dtl_Proc (P_RS OUT RESULTSET);
             PROCEDURE MULTI_QUOTE_SEL_BUY_RATE_PROC(P_ORG_LOC VARCHAR2,
					  P_DEST_LOC VARCHAR2,
					  P_TERMINAL VARCHAR2,
					  P_SRVLEVEL VARCHAR2, P_SHMODE VARCHAR2,
					  P_PERMISSION VARCHAR2 DEFAULT 'Y',
					  P_OPERATION VARCHAR2,
					  P_QUOTE_ID VARCHAR2,
            P_WEIGHT_BREAK VARCHAR2,
					  P_RS OUT RESULTSET);
      PROCEDURE QUOTE_SELL_BUY_RATES_PROC(P_ORG_LOC VARCHAR2,
					  P_DEST_LOC VARCHAR2,
					  P_TERMINAL VARCHAR2,
					  P_SRVLEVEL VARCHAR2, P_SHMODE VARCHAR2,
					  P_PERMISSION VARCHAR2 DEFAULT 'Y',
					  P_OPERATION VARCHAR2,
					  P_QUOTE_ID VARCHAR2,
					  P_RS OUT RESULTSET);

      PROCEDURE QUOTE_SELL_BUY_CHARGES_PROC(P_CHARGEGRPS VARCHAR2,
					    P_SALESPERSONCODE VARCHAR2,
					    P_TERMINALID VARCHAR2,
					    P_PERMISSION VARCHAR2 DEFAULT 'Y',
					    P_MARGIN NUMBER, P_DISCOUNT NUMBER,
					    P_ORIGIN VARCHAR2,
					    P_DESTINATION VARCHAR2,
					    P_SHMODE VARCHAR2,
					    P_CUSTOMERID VARCHAR2,
					    P_OPERATION VARCHAR2,
					    P_QUOTE_ID VARCHAR2,
					    P_RS OUT RESULTSET);

      PROCEDURE QUOTE_SELL_BUY_RATESDTL_PROC(P_ORGLOC VARCHAR2,
					     P_DESTLOC VARCHAR2,
					     P_SELL_BUY_RATEID VARCHAR2,
					     P_BUY_RATE_ID VARCHAR2,
					     P_LANENO VARCHAR2,
					     P_SALESPERSONCODE VARCHAR2,
					     P_TERMINALID VARCHAR2,
					     P_PERMISSION VARCHAR2 DEFAULT 'Y',
					     P_SELLRATE_FLAG VARCHAR2 DEFAULT 'Y',
					     P_MARGIN NUMBER,
					     P_OPERATION VARCHAR2,
					     P_QUOTE_ID VARCHAR2,
					     P_CUSTOMERID VARCHAR2,
					     P_QUOTE_ORG VARCHAR2,
					     P_QUOTE_DEST VARCHAR2,
					     P_CARRIER VARCHAR2,
					     P_SERVICELEVEL VARCHAR2,
					     P_FREQUENCY VARCHAR2,
					     P_FREIGHTRATETERM VARCHAR2,
					     P_SHMODE VARCHAR2,
					     P_RS OUT RESULTSET);

      PROCEDURE QUOTE_SELL_BUY_CARTAGES_PROC(P_SHZIPCODE VARCHAR2 DEFAULT '',
					     P_SHZONES VARCHAR2,
					     P_CONSIGNZIPCODE VARCHAR2 DEFAULT '',
					     P_CONSIGNZONES VARCHAR2,
					     P_SALESPERSONCODE VARCHAR2,
					     P_TERMINALID VARCHAR2,
					     P_PERMISSION VARCHAR2 DEFAULT 'Y',
					     P_QUOTE_ORIGIN VARCHAR2,
					     P_QUOTE_DESTINATION VARCHAR2,
					     P_MARGIN NUMBER, P_DISCOUNT NUMBER,
					     P_CUSTOMERID VARCHAR2,
					     P_SHMODE VARCHAR2,
					     P_SHIPPER_MODE VARCHAR2,
					     P_SHIPPR_CNSL_TYPE VARCHAR2,
					     P_CONSIGNEE_MODE VARCHAR2,
					     P_CONSGNEE_CNSL_TYPE VARCHAR2,
					     P_OPERATION VARCHAR2,
					     P_QUOTE_ID VARCHAR2,
					     P_RS OUT RESULTSET,
					     P_RS2 OUT RESULTSET,
					     P_RS3 OUT RESULTSET,
					     --Distinct Pickup Charge slabs
					     P_RS4 OUT RESULTSET
					     --Distinct Delivery Charge slabs
					     );

      PROCEDURE QUOTE_VIEW_PROC(P_QUOTEID VARCHAR2,P_LANE_NO VARCHAR2, P_RS OUT RESULTSET,
				P_RS1 OUT RESULTSET, P_RS2 OUT RESULTSET,
				P_RS3 OUT RESULTSET);

      /*PROCEDURE quoteid_lov(p_customerid   VARCHAR2,
      p_origin       VARCHAR2,
      p_destination  VARCHAR2,
      p_terminalid   VARCHAR2,
      p_searchstring VARCHAR2,
      p_rs           OUT resultset);*/
      PROCEDURE TIED_CUSTINFO_CHARGES_PROC(P_CUSTOMERID VARCHAR2,
					   P_ORIGIN VARCHAR2,
					   P_DESTINATION VARCHAR2,
					   P_TERMINALID VARCHAR2,
					   P_SHMODE VARCHAR2, P_FLAG VARCHAR2,
					   P_OPERATION VARCHAR2,
					   P_QUOTE_ID VARCHAR2,
					   P_CHARGEGRPS VARCHAR2); --@@Modified by Kameswari for the WPBN issues-80162,80018
      PROCEDURE TIED_CUSTINFO_FREIGHT_PROC(P_CUSTOMERID VARCHAR2,
					   P_ORIGIN VARCHAR2,
					   P_DESTINATION VARCHAR2,
					   P_CARRIER VARCHAR2,
					   P_SERVICELEVEL VARCHAR2,
					   P_FREQUENCY VARCHAR2,
					   P_FREIGHTRATETERM VARCHAR2,
					   P_TERMINALID VARCHAR2,
					   P_SHMODE VARCHAR2, P_FLAG VARCHAR2,
					   P_QUOTE_ORG VARCHAR2,
					   P_QUOTE_DEST VARCHAR2,
					   P_OPERATION VARCHAR2,
					   P_QUOTE_ID VARCHAR2);

      PROCEDURE TIED_CUSTINFO_CARTAGES_PROC(P_CUSTOMERID VARCHAR2,
					    P_ORIGIN VARCHAR2,
					    P_DESTINATION VARCHAR2,
					    P_TERMINALID VARCHAR2,
					    P_SHMODE VARCHAR2, P_FLAG VARCHAR2,
					    P_SHZONE VARCHAR2,
					    P_CONSZONE VARCHAR2,
					    P_SHIPPER_MODE VARCHAR2,
					    P_SHPPR_CNSL_TYPE VARCHAR2,
					    P_CNSGNEE_MODE VARCHAR2,
					    P_CNSGNEE_CNSL_TYPE VARCHAR2,
					    P_OPERATION VARCHAR2,
					    P_QUOTE_ID VARCHAR2);

      PROCEDURE QMS_UPDATED_QUOTES_COUNT(P_TERMINALID VARCHAR2,
					 P_USERID VARCHAR2, P_EMPID VARCHAR2,
					 P_RS OUT RESULTSET);

      PROCEDURE QMS_UPDATED_QUOTES_INFO(P_CHANGE_DESC VARCHAR2,
					P_TERMINALID VARCHAR2,
					P_PAGE_NO NUMBER DEFAULT 1,
					P_PAGE_ROWS NUMBER DEFAULT 20,
					SORTBY VARCHAR2, SORTORDER VARCHAR2,
					P_USERID VARCHAR2, P_EMPID VARCHAR2,
					P_TOT_REC OUT NUMBER,
					P_TOT_PAGES OUT NUMBER,
					P_RS OUT RESULTSET);

      PROCEDURE UPDATED_QUOTE_INFO_MODIFY(P_QUOTEID VARCHAR2,
					  P_SELLBUYFLAG VARCHAR2,
					  --modified by subrahmanyam for 146970 ,146971
					  P_TERMINALID VARCHAR2,
					  P_RS OUT RESULTSET,
					  P_RS1 OUT RESULTSET,
					  P_RS2 OUT RESULTSET,
					  P_RS3 OUT RESULTSET);

      PROCEDURE QMS_UPDATED_QUOTES_INFO_EXCEL(P_CHANGE_DESC VARCHAR2,
					      P_TERMINALID VARCHAR2,
					      P_USERID VARCHAR2,
					      P_EMPID VARCHAR2,
					      P_RS OUT RESULTSET);

			PROCEDURE MULTI_QUOTE_VIEW_PROC(P_QUOTEID VARCHAR2, P_RS OUT RESULTSET,
				P_RS1 OUT RESULTSET, P_RS2 OUT RESULTSET,
				P_RS3 OUT RESULTSET/*,P_RS4 OUT RESULTSET*/);

        PROCEDURE UPDATED_MULTI_QUOTE_INF_MODIFY(P_ID    VARCHAR2,
                                       P_QUOTEID    VARCHAR2,
                                      P_SELLBUYFLAG VARCHAR2, --modified by subrahmanyam for 146971 , 146970
                                      P_TERMINALID  VARCHAR2,
                                     -- p_unique_id   number, --kishore
                                      P_RS          OUT RESULTSET,
                                      P_RS1         OUT RESULTSET,
                                      P_RS2         OUT RESULTSET,
                                      P_RS3         OUT RESULTSET);
        PROCEDURE MULTI_QUOTE_SEL_BUY_RTE_PROC(P_ORG_LOC VARCHAR2,
					  P_DEST_LOC VARCHAR2,
					  P_TERMINAL VARCHAR2,
					  P_SRVLEVEL VARCHAR2, P_SHMODE VARCHAR2,
					  P_PERMISSION VARCHAR2 DEFAULT 'Y',
					  P_OPERATION VARCHAR2,
					  P_QUOTE_ID VARCHAR2,
            P_WEIGHT_BREAK VARCHAR2,
					  P_RS OUT RESULTSET);

       -- Added By Kishroe Podili for 25Feb11
       PROCEDURE SINGLE_QUOTE_SEL_BUY_RATE_PROC(P_ORG_LOC VARCHAR2,
					  P_DEST_LOC VARCHAR2,
					  P_TERMINAL VARCHAR2,
					  P_SRVLEVEL VARCHAR2, P_SHMODE VARCHAR2,
					  P_PERMISSION VARCHAR2 DEFAULT 'Y',
					  P_OPERATION VARCHAR2,
					  P_QUOTE_ID VARCHAR2,
            P_WEIGHT_BREAK VARCHAR2,
					  P_RS OUT RESULTSET);


	PROCEDURE MULTI_QUOTE_DETAILED_VIEW_PROC(P_QUOTEID VARCHAR2, P_RS OUT RESULTSET
				                                 );
   PROCEDURE MULTI_QUOTE_SPOT_RATE_PROC(
    P_ORG_LOC      VARCHAR2,
    P_DEST_LOC     VARCHAR2,
    P_TERMINAL     VARCHAR2,
    P_SRVLEVEL     VARCHAR2,
    P_SHMODE       VARCHAR2,
    P_PERMISSION   VARCHAR2 DEFAULT 'Y',
    P_OPERATION    VARCHAR2,
    P_QUOTE_ID     VARCHAR2,
    P_WEIGHT_BREAK VARCHAR2,
    P_LANENO       NUMBER,
    singleReturn   OUT RESULTSET,
    multipleReturn OUT RESULTSET);



    FUNCTION MULTI_QUOTE_BASIS(P_SHIPMENT_MODE VARCHAR2,
                               P_CONSOLE_TYPE VARCHAR2,
                               P_WEIGHTBREAK  VARCHAR2 ) RETURN VARCHAR2;



END;

/

/
