--------------------------------------------------------
--  DDL for Procedure QUOTES_ARCHIVE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "QUOTES_ARCHIVE" is

    V_QUOTE_ID VARCHAR2(1000);

      v_max  varchar2(1000);
begin


 FOR I IN ( SELECT QUOTE_ID FROM QMS_QUOTE_MASTER WHERE INSTR(QUOTE_ID,'_',1,2) >0  and terminal_id  in ('DHLAKL') ) LOOP

 --dbms_output.put_line(i.quote_id );

select substr(I.QUOTE_ID,1,instr(I.QUOTE_ID,'_',1,2)-1)INTO V_QUOTE_ID from dual;

select max(qms.quote_id)into v_max from qms_quote_master qms where qms.quote_id like ''||V_QUOTE_ID||'%'||'';

 --dbms_output.put_line(I.QUOTE_ID ||'-----'||v_max );

 IF I.QUOTE_ID != V_MAX THEN

DELETE FROM QMS_QUOTE_SPOTRATES WHERE QUOTE_ID IN (SELECT ID FROM QMS_QUOTE_MASTER WHERE QUOTE_ID IN (I.QUOTE_ID));
DELETE FROM QMS_QUOTE_ATTACHMENTDTL WHERE QUOTE_ID IN (SELECT ID FROM QMS_QUOTE_MASTER WHERE QUOTE_ID IN (I.QUOTE_ID));
DELETE FROM QMS_QUOTE_HF_DTL WHERE QUOTE_ID IN (SELECT ID FROM QMS_QUOTE_MASTER WHERE QUOTE_ID IN (I.QUOTE_ID));
DELETE FROM QMS_QUOTE_CONTACTDTL WHERE QUOTE_ID IN (SELECT ID FROM QMS_QUOTE_MASTER WHERE QUOTE_ID IN (I.QUOTE_ID));
DELETE FROM QMS_QUOTE_NOTES WHERE QUOTE_ID IN (SELECT ID FROM QMS_QUOTE_MASTER WHERE QUOTE_ID IN (I.QUOTE_ID));
DELETE FROM QMS_QUOTE_CHARGEGROUPDTL WHERE QUOTE_ID IN (SELECT ID FROM QMS_QUOTE_MASTER WHERE QUOTE_ID IN (I.QUOTE_ID));
DELETE FROM QMS_QUOTE_RATES WHERE QUOTE_ID IN (SELECT ID FROM QMS_QUOTE_MASTER WHERE QUOTE_ID IN (I.QUOTE_ID));
DELETE FROM QMS_QUOTES_UPDATED WHERE QUOTE_ID IN (SELECT ID FROM QMS_QUOTE_MASTER WHERE QUOTE_ID IN (I.QUOTE_ID));
DELETE FROM QMS_QUOTE_MASTER WHERE QUOTE_ID IN (I.QUOTE_ID);
COMMIT;
/*DELETE FROM FS_RT_LEG WHERE RT_PLAN_ID IN (SELECT RT_PLAN_ID FROM FS_RT_PLAN WHERE QUOTE_ID IN (I.QUOTE_ID));
DELETE FROM FS_RT_PLAN WHERE QUOTE_ID IN (I.QUOTE_ID);
COMMIT;*/


 END IF;

 END LOOP;
  COMMIT;
end QUOTES_ARCHIVE;

/

/
