--------------------------------------------------------
--  DDL for Package Body UOM_UTILS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "UOM_UTILS" 
AS
/*
 *  Using this function for calculate weight according to uom
 *  passing the in parameters are
 *  WEIGHT      NUMBER;
 *  SOURCE_UOW  VARCHAR2;
 *  TARGET_UOW  VARCHAR2;
 *  RETURN NUMBER IS CONVERTEDWEIGHT NUMBER;
 */
	FUNCTION
	CONVERT_WEIGHT(WEIGHT NUMBER,SOURCE_UOW VARCHAR2,TARGET_UOW VARCHAR2)
	RETURN NUMBER IS CONVERTEDWEIGHT NUMBER;

	BEGIN
	IF SOURCE_UOW = TARGET_UOW THEN
	 CONVERTEDWEIGHT  := WEIGHT ;
	ELSIF SOURCE_UOW='KG' AND TARGET_UOW='LB' THEN
	 CONVERTEDWEIGHT  := WEIGHT*2.2;
	ELSIF SOURCE_UOW='LB' AND TARGET_UOW='KG' THEN
	 CONVERTEDWEIGHT  := WEIGHT/2.2;
	END IF;
	RETURN CONVERTEDWEIGHT;

	END CONVERT_WEIGHT;

/*
 *  Using this function for calculate volume according to uom
 *  passing the in parameters are
 *  VOLUME      NUMBER;
 *  SOURCE_UOV  VARCHAR2;
 *  TARGET_UOV  VARCHAR2;
 *  RETURN  NUMBER IS CONVERTEDVOLUME NUMBER;
 */
	FUNCTION
	CONVERT_VOLUME(VOLUME NUMBER,SOURCE_UOV VARCHAR2,
		      TARGET_UOV VARCHAR2)
	RETURN NUMBER IS CONVERTEDVOLUME NUMBER;

	BEGIN
	IF SOURCE_UOV = TARGET_UOV THEN
	 CONVERTEDVOLUME  := VOLUME ;
	ELSIF SOURCE_UOV='CBM' AND TARGET_UOV='CFT' THEN
	 CONVERTEDVOLUME  := VOLUME*(116.5/3.3);
	ELSIF SOURCE_UOV='CFT' AND TARGET_UOV='CBM' THEN
	 CONVERTEDVOLUME  := VOLUME*(3.3/116.5);
	END IF;
	RETURN CONVERTEDVOLUME;

	END CONVERT_VOLUME;

/*
 *  Using this function for convert valume to weight according to uom
 *  passing the in parameters are
 *  VOLUME              NUMBER;
 *  SOURCE_UOV          VARCHAR2;
 *  TARGET_UOW          VARCHAR2;
 *  TARGET_SHIPMENTMODE NUMBER;
 *  RETURN  EQUIVALENTWEIGHT;
 */
	FUNCTION
	CONVERT_VOLUME_TO_WEIGHT(VOLUME NUMBER,SOURCE_UOV VARCHAR2,
		      TARGET_UOW VARCHAR2, TARGET_SHIPMENTMODE NUMBER)
	RETURN NUMBER IS EQUIVALENTWEIGHT NUMBER;

	BEGIN
		IF TARGET_SHIPMENTMODE = 1 THEN
			IF SOURCE_UOV = 'CBM' AND TARGET_UOW = 'KG' THEN
				EQUIVALENTWEIGHT  := VOLUME*(1000/6) ;
			ELSIF SOURCE_UOV = 'CFT' AND TARGET_UOW = 'KG' THEN
				EQUIVALENTWEIGHT  := VOLUME*(1000/(6*35.3));

			ELSIF SOURCE_UOV = 'CBM' AND TARGET_UOW = 'LB' THEN
				EQUIVALENTWEIGHT  := VOLUME*(2200/6) ;
			ELSIF SOURCE_UOV = 'CFT' AND TARGET_UOW = 'LB' THEN
				EQUIVALENTWEIGHT  := VOLUME*(2200/(6*35.3));
			END IF;
		ELSIF TARGET_SHIPMENTMODE = 2 THEN
			IF SOURCE_UOV = 'CBM' AND TARGET_UOW = 'KG' THEN
				EQUIVALENTWEIGHT  := VOLUME*(1000) ;
			ELSIF SOURCE_UOV = 'CFT' AND TARGET_UOW = 'KG' THEN
				EQUIVALENTWEIGHT  := VOLUME*(1000/35.3);

			ELSIF SOURCE_UOV = 'CBM' AND TARGET_UOW = 'LB' THEN
				EQUIVALENTWEIGHT  := VOLUME*(1000*2.2) ;
			ELSIF SOURCE_UOV = 'CFT' AND TARGET_UOW = 'LB' THEN
				EQUIVALENTWEIGHT  := VOLUME*(1000*2.2/35.3);
			END IF;
		ELSIF TARGET_SHIPMENTMODE = 4 THEN
			IF SOURCE_UOV = 'CBM' AND TARGET_UOW = 'KG' THEN
				EQUIVALENTWEIGHT  := VOLUME*(1000/3.3) ;
			ELSIF SOURCE_UOV = 'CFT' AND TARGET_UOW = 'KG' THEN
				EQUIVALENTWEIGHT  := VOLUME*(1000/116.5);

			ELSIF SOURCE_UOV = 'CBM' AND TARGET_UOW = 'LB' THEN
				EQUIVALENTWEIGHT  := VOLUME*((1000*2.2)/3.3) ;
			ELSIF SOURCE_UOV = 'CFT' AND TARGET_UOW = 'LB' THEN
				EQUIVALENTWEIGHT  := VOLUME*(1000*2.2/116.5);
			END IF;
		END IF;
	RETURN EQUIVALENTWEIGHT;

	END CONVERT_VOLUME_TO_WEIGHT;

/*
 *  Using this function for convert weight to valume according to uom
 *  passing the in parameters are
 *  WEIGHT              NUMBER;
 *  SOURCE_UOW          VARCHAR2;
 *  TARGET_UOV          VARCHAR2;
 *  TARGET_SHIPMENTMODE NUMBER;
 *  RETURN  EQUIVALENTVOLUME;
 */
	FUNCTION
	CONVERT_WEIGHT_TO_VOLUME(WEIGHT NUMBER,SOURCE_UOW VARCHAR2,
		      TARGET_UOV VARCHAR2, TARGET_SHIPMENTMODE NUMBER)
	RETURN NUMBER IS EQUIVALENTVOLUME NUMBER;

	BEGIN
		IF TARGET_SHIPMENTMODE = 1 THEN
			IF TARGET_UOV = 'CBM' AND SOURCE_UOW = 'KG' THEN
				EQUIVALENTVOLUME  := WEIGHT/(1000/6) ;
			ELSIF TARGET_UOV = 'CFT' AND SOURCE_UOW = 'KG' THEN
				EQUIVALENTVOLUME  := WEIGHT/(1000/(6*35.3));

			ELSIF TARGET_UOV = 'CBM' AND SOURCE_UOW = 'LB' THEN
				EQUIVALENTVOLUME  := WEIGHT/(2200/6) ;
			ELSIF TARGET_UOV = 'CFT' AND SOURCE_UOW = 'LB' THEN
				EQUIVALENTVOLUME  := WEIGHT/(2200/(6*35.3));
			END IF;
		ELSIF TARGET_SHIPMENTMODE = 2 THEN
			IF TARGET_UOV = 'CBM' AND SOURCE_UOW = 'KG' THEN
				EQUIVALENTVOLUME  := WEIGHT/(1000) ;
			ELSIF TARGET_UOV = 'CFT' AND SOURCE_UOW = 'KG' THEN
				EQUIVALENTVOLUME  := WEIGHT/(1000/35.3);

			ELSIF TARGET_UOV = 'CBM' AND SOURCE_UOW = 'LB' THEN
				EQUIVALENTVOLUME  := WEIGHT/(1000*2.2) ;
			ELSIF TARGET_UOV = 'CFT' AND SOURCE_UOW = 'LB' THEN
				EQUIVALENTVOLUME  := WEIGHT/(1000*2.2/35.3);
			END IF;
		ELSIF TARGET_SHIPMENTMODE = 4 THEN
			IF TARGET_UOV = 'CBM' AND SOURCE_UOW = 'KG' THEN
				EQUIVALENTVOLUME  := WEIGHT/(1000/3.3) ;
			ELSIF TARGET_UOV = 'CFT' AND SOURCE_UOW = 'KG' THEN
				EQUIVALENTVOLUME  := WEIGHT/(1000/116.5);

			ELSIF TARGET_UOV = 'CBM' AND SOURCE_UOW = 'LB' THEN
				EQUIVALENTVOLUME  := WEIGHT/((1000*2.2)/3.3) ;
			ELSIF TARGET_UOV = 'CFT' AND SOURCE_UOW = 'LB' THEN
				EQUIVALENTVOLUME  := WEIGHT/(1000*2.2/116.5);
			END IF;
		END IF;
	RETURN EQUIVALENTVOLUME;
	END CONVERT_WEIGHT_TO_VOLUME;
END UOM_UTILS;

/

/
