package com.foursoft.esupply.accesscontrol.ejb.bmp;

/* ***********************************************
* Generated by Pramati Technologies, EJBWizard 
* Generation of PrimaryKey Class of the com.foursoft.esupply.accesscontrol.ejb.bmp.RoleMasterBeanPK
* Mon Nov 26 18:00:47 IST 2001
* ************************************************/

public class RoleMasterBeanPK
	implements java.io.Serializable

{

	public		java.lang.String	roleId;
	public		java.lang.String	locationId;
		
		
	public boolean equals(Object obj){
		RoleMasterBeanPK pkObj = (RoleMasterBeanPK)obj;
		//System.out.println("pppppppppppppppppproleId="+roleId+" pkObj.roleId="+pkObj.roleId);

		return (roleId.equals(pkObj.roleId) && locationId.equals(pkObj.locationId));		
	}
	
	public int hashCode(){
		try {
			long	crcKey = -1;
			java.io.ByteArrayOutputStream bos = new java.io.ByteArrayOutputStream();
			java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(bos);
			oos.writeObject(this);
			oos.flush();
			java.util.zip.Adler32 adl32 = new java.util.zip.Adler32();
			adl32.update(bos.toByteArray());
			crcKey = adl32.getValue();
			return (int)(crcKey ^ (crcKey >> 32));
		} catch (java.io.IOException ioEx) {
			return -1;
		}
	}
}
