package com.foursoft.esupply.accesscontrol.ejb.bmp;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* HomeInterface Class of the com.foursoft.esupply.accesscontrol.ejb.bmp.RoleMasterBean *
* Sun Feb 16 12:46:21 IST 2003
* ***********************************************/

import java.rmi.RemoteException;
import javax.ejb.*;
import com.foursoft.esupply.accesscontrol.java.RoleModel;

public interface RoleMasterHome extends javax.ejb.EJBHome
{
	public RoleMaster create(RoleModel param0) throws javax.ejb.CreateException, java.rmi.RemoteException;
	public RoleMaster findByPrimaryKey(RoleMasterBeanPK param0) throws javax.ejb.FinderException, java.rmi.RemoteException;
}
