package com.foursoft.esupply.accesscontrol.ejb.bmp;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* HomeInterface Class of the com.foursoft.esupply.accesscontrol.ejb.bmp.RoleMasterBean *
* Sun Feb 16 12:46:21 IST 2003
* ***********************************************/

import javax.ejb.EJBLocalHome;
import com.foursoft.esupply.accesscontrol.java.RoleModel;

public interface RoleMasterLocalHome extends EJBLocalHome
{
	public RoleMasterLocal create(RoleModel param0) throws javax.ejb.CreateException;
	public RoleMasterLocal findByPrimaryKey(RoleMasterBeanPK param0) throws javax.ejb.FinderException;
}
