package com.foursoft.esupply.accesscontrol.ejb.bmp;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* RemoteInterface Class of the com.foursoft.esupply.accesscontrol.ejb.bmp.UserMasterBean *
* Sun Feb 16 12:46:59 IST 2003
* ***********************************************/

import javax.ejb.EJBLocalObject;
import com.foursoft.esupply.accesscontrol.exception.DataIntegrityViolationException;

public interface UserMasterLocal extends EJBLocalObject
{
	public  com.foursoft.esupply.accesscontrol.java.UserModel getUserModel();
	public  void setUserModel(com.foursoft.esupply.accesscontrol.java.UserModel param0) throws DataIntegrityViolationException;
}
