package com.foursoft.esupply.accesscontrol.ejb.bmp;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* HomeInterface Class of the com.foursoft.esupply.accesscontrol.ejb.bmp.UserMasterBean *
* Sun Feb 16 12:46:59 IST 2003
* ***********************************************/

import java.rmi.RemoteException;
import javax.ejb.EJBLocalHome;
import com.foursoft.esupply.accesscontrol.java.UserModel;
public interface UserMasterLocalHome extends EJBLocalHome
{
	public UserMasterLocal create(UserModel param0) throws javax.ejb.CreateException;
	public UserMasterLocal findByPrimaryKey(UserMasterBeanPK param0) throws javax.ejb.FinderException;
}
