package com.foursoft.esupply.accesscontrol.ejb.bmp;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* HomeInterface Class of the com.foursoft.esupply.accesscontrol.ejb.bmp.UserMasterBean *
* Sun Feb 16 12:46:59 IST 2003
* ***********************************************/

import java.rmi.RemoteException;
import javax.ejb.*;

public interface UserMasterHome extends javax.ejb.EJBHome
{
	public com.foursoft.esupply.accesscontrol.ejb.bmp.UserMaster create (com.foursoft.esupply.accesscontrol.java.UserModel param0)
		throws javax.ejb.CreateException, java.rmi.RemoteException;
	public com.foursoft.esupply.accesscontrol.ejb.bmp.UserMaster	findByPrimaryKey(com.foursoft.esupply.accesscontrol.ejb.bmp.UserMasterBeanPK param0)
			throws javax.ejb.FinderException, java.rmi.RemoteException;
}
