package com.foursoft.esupply.accesscontrol.ejb.sls;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* HomeInterface Class of the com.foursoft.esupply.accesscontrol.ejb.sls.AccessControlSessionBean *
* Thu Mar 06 19:00:15 IST 2003
* ***********************************************/

import javax.ejb.EJBLocalHome;

public interface AccessControlSessionLocalHome extends EJBLocalHome
{
	public AccessControlSessionLocal create () throws javax.ejb.CreateException;
}
