package com.foursoft.esupply.accesscontrol.ejb.sls;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* RemoteInterface Class of the com.foursoft.esupply.accesscontrol.ejb.sls.AccessControlSessionBean *
* Thu Mar 06 19:00:15 IST 2003
* ***********************************************/

import java.rmi.RemoteException;
import javax.ejb.EJBObject;
import com.foursoft.esupply.common.exception.FoursoftException;

public interface AccessControlSession extends EJBObject
{
	public  java.lang.String getELogCurrencyId(java.lang.String param0, java.lang.String param1)
		throws java.rmi.RemoteException, FoursoftException;
	public  com.foursoft.esupply.common.bean.ESupplyGlobalParameters getESupplyGlobalParameters(java.lang.String param0, java.lang.String param1, java.lang.String param2, java.lang.String param3)
		throws java.rmi.RemoteException, com.foursoft.esupply.accesscontrol.exception.InvalidUserException, FoursoftException;
	public  java.lang.String getETransCurrencyId(java.lang.String param0)
		throws java.rmi.RemoteException, FoursoftException;
	public  java.util.Hashtable getOptionalRolePermissions(java.lang.String param0, java.lang.String param1, java.lang.String param2)
		throws java.rmi.RemoteException, FoursoftException;
	public  java.util.Hashtable getRolePermissions(java.lang.String param0, java.lang.String param1) 
		throws java.rmi.RemoteException, FoursoftException;
	public  java.lang.Integer getTerminalType(java.lang.String param0, java.lang.String param1)
		throws java.rmi.RemoteException, FoursoftException;
	public  com.foursoft.eaccounts.common.java.AccountsCredentials prepareAccountsCredentials(java.lang.String param0, java.lang.String param1)
		throws java.rmi.RemoteException, FoursoftException;
	public  com.foursoft.esupply.common.bean.ESupplyGlobalParameters verifyELogCRMVRMUser(java.lang.String param0, java.lang.String param1, java.lang.String param2, java.lang.String param3)
		throws java.rmi.RemoteException, com.foursoft.esupply.accesscontrol.exception.InvalidUserException, FoursoftException;
	public  com.foursoft.esupply.common.bean.ESupplyGlobalParameters verifyETransCRMUser(java.lang.String param0, java.lang.String param1, java.lang.String param2, java.lang.String param3)
		throws java.rmi.RemoteException, com.foursoft.esupply.accesscontrol.exception.InvalidUserException, FoursoftException;
	public  com.foursoft.esupply.common.bean.ESupplyGlobalParameters verifySPCRMVRMUser(java.lang.String param0, java.lang.String param1, java.lang.String param2, java.lang.String param3)
		throws java.rmi.RemoteException, com.foursoft.esupply.accesscontrol.exception.InvalidUserException, FoursoftException;

    boolean getPasswordModifiedDate(String userId, String locationId) throws FoursoftException, RemoteException;
	boolean getLoginCount(String userId, String locationId) throws FoursoftException, RemoteException;
	public int getNoFailAttempts() throws FoursoftException,RemoteException;
    boolean getWarningCountExceeded(String userId, String locationId) throws FoursoftException, RemoteException;
	public boolean lockUser(String userId, String locationId) throws FoursoftException, RemoteException;
	public boolean unlockUser(String userId, String locationId) throws FoursoftException, RemoteException;
	public boolean logOutUpdate(String userId, String locationId) throws FoursoftException, RemoteException;
}
