package com.foursoft.esupply.accesscontrol.ejb.sls;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* RemoteInterface Class of the com.foursoft.esupply.accesscontrol.ejb.sls.AccessControlSessionBean *
* Thu Mar 06 19:00:15 IST 2003
* ***********************************************/

import javax.ejb.EJBLocalObject;
import com.foursoft.esupply.common.exception.FoursoftException;
import com.foursoft.esupply.accesscontrol.exception.InvalidUserException;
import com.foursoft.esupply.common.bean.ESupplyGlobalParameters;

public interface AccessControlSessionLocal extends EJBLocalObject
{
	public String getELogCurrencyId(String param0, String param1) throws FoursoftException;
	public ESupplyGlobalParameters getESupplyGlobalParameters(String param0, String param1, String param2, String param3) throws InvalidUserException, FoursoftException;
	public String getETransCurrencyId(String param0) throws FoursoftException;
	public java.util.Hashtable getOptionalRolePermissions(String param0, String param1, String param2) throws FoursoftException;
	public java.util.Hashtable getRolePermissions(String param0, String param1) throws FoursoftException;
	public java.lang.Integer getTerminalType(String param0, String param1) throws FoursoftException;
	public com.foursoft.eaccounts.common.java.AccountsCredentials prepareAccountsCredentials(String param0, String param1) throws FoursoftException;
	public com.foursoft.esupply.common.bean.ESupplyGlobalParameters verifyELogCRMVRMUser(String param0, String param1, String param2, String param3) throws com.foursoft.esupply.accesscontrol.exception.InvalidUserException, FoursoftException;
	public com.foursoft.esupply.common.bean.ESupplyGlobalParameters verifyETransCRMUser(String param0, String param1, String param2, String param3) throws com.foursoft.esupply.accesscontrol.exception.InvalidUserException, FoursoftException;
	public com.foursoft.esupply.common.bean.ESupplyGlobalParameters verifySPCRMVRMUser(String param0, String param1, String param2, String param3) throws com.foursoft.esupply.accesscontrol.exception.InvalidUserException, FoursoftException;

    boolean getPasswordModifiedDate(String userId, String locationId) throws FoursoftException;

    boolean getWarningCountExceeded(String userId, String locationId) throws FoursoftException;
}
