package com.foursoft.esupply.accesscontrol.ejb.sls;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* RemoteInterface Class of the com.foursoft.esupply.accesscontrol.ejb.sls.UserRoleRegistrationSessionBean *
* Thu Mar 06 11:13:56 IST 2003
* ***********************************************/

import java.rmi.RemoteException;
import javax.ejb.EJBObject;
import com.foursoft.esupply.common.exception.FoursoftException;
import java.util.ArrayList;
import com.foursoft.esupply.accesscontrol.exception.DataIntegrityViolationException;
import com.foursoft.esupply.accesscontrol.exception.NotExistsException;

public interface UserRoleRegistrationSession extends EJBObject
{
	public  boolean removeRole(java.lang.String param0, java.lang.String param1, java.lang.String param2, java.lang.String param3)
		throws java.rmi.RemoteException, com.foursoft.esupply.accesscontrol.exception.DataIntegrityViolationException, FoursoftException;
	public  java.util.ArrayList getRolePermissions(java.lang.String param0, java.lang.String param1)
		throws java.rmi.RemoteException, FoursoftException;
	public  int changePassword(java.lang.String param0, java.lang.String param1, java.lang.String param2, java.lang.String param3, java.lang.String param4)
		throws java.rmi.RemoteException, FoursoftException;
	public  java.util.Hashtable getAllRolePermissions(java.lang.String param0, java.lang.String param1)
		throws java.rmi.RemoteException, FoursoftException;
	public  java.util.ArrayList getLocationIds(java.lang.String param0, java.lang.String param1, java.lang.String param2, java.lang.String param3)
		throws java.rmi.RemoteException,FoursoftException;
	public  java.util.ArrayList getRoleIdLocDescription(java.lang.String param0, java.lang.String param1, java.lang.String param2)
		throws java.rmi.RemoteException,FoursoftException;
	public  java.util.ArrayList getRoleIdLocation(java.lang.String param0, java.lang.String param1, java.lang.String param2, java.lang.String param3, java.lang.String param4, java.lang.String param5, java.lang.String param6)
		throws java.rmi.RemoteException,FoursoftException;
	public  java.util.ArrayList getRoleIds(java.lang.String param0, java.lang.String param1, java.lang.String param2)
		throws java.rmi.RemoteException,FoursoftException;
	public  com.foursoft.esupply.accesscontrol.java.RoleModel getRoleModel(java.lang.String param0, java.lang.String param1)
		throws java.rmi.RemoteException,FoursoftException,NotExistsException;
	public  java.util.ArrayList getRoleViewAllInformation()	throws java.rmi.RemoteException,FoursoftException;
	public  java.util.ArrayList getRoleViewAllInformation(String locationId)	throws java.rmi.RemoteException,FoursoftException;
	public  java.util.ArrayList getTransactionDetailVOBs(java.lang.String param0, java.lang.String param1)
		throws java.rmi.RemoteException,FoursoftException;
	public  java.util.ArrayList getTransactionDetailVOBs(java.lang.String param0, int param1, java.lang.String param2)
		throws java.rmi.RemoteException,FoursoftException;
	public  java.util.ArrayList getTransactionDetailVOBs(java.lang.String param0)
		throws java.rmi.RemoteException,FoursoftException;
	public  java.util.Hashtable getTransactionIdAndDescription(java.lang.String param0)
		throws java.rmi.RemoteException,FoursoftException;
	public  java.util.Hashtable getTransactionIdAndDescription()
		throws java.rmi.RemoteException,FoursoftException;
	public  java.util.ArrayList getTransactionIds(java.lang.String param0, int param1, java.lang.String param2)
		throws java.rmi.RemoteException,FoursoftException;
	public  java.util.ArrayList getTransactionIds()
		throws java.rmi.RemoteException,FoursoftException;
	public  java.util.ArrayList getTransactionIds(java.lang.String param0, java.lang.String param1)
		throws java.rmi.RemoteException,FoursoftException;
	public  java.util.ArrayList getTransactionIds(java.lang.String param0)
		throws java.rmi.RemoteException,FoursoftException;
//Commented by subrahmanyam for enhancement 154384 on 10/04/09    
	/*public  java.util.ArrayList getUserIds(java.lang.String param0, java.lang.String param1, java.lang.String param2)
		throws java.rmi.RemoteException, FoursoftException;*/
//Added by subrahmanyam for enhancement 154384 on 10/04/09        
    public  java.util.ArrayList getUserIds(java.lang.String param0, java.lang.String param1, java.lang.String param2,java.lang.String terminalid,java.lang.String terminalType)
		throws java.rmi.RemoteException, FoursoftException;
	public  java.util.ArrayList getUserIds(java.lang.String param0)
		throws java.rmi.RemoteException, FoursoftException;
	public  com.foursoft.esupply.accesscontrol.java.UserModel getUserInformation(java.lang.String param0, java.lang.String param1)
		throws java.rmi.RemoteException, com.foursoft.esupply.accesscontrol.exception.NotExistsException,FoursoftException;
	public  java.util.ArrayList getUserLogDetails(java.lang.String param0, java.lang.String param1, java.sql.Timestamp param2, java.sql.Timestamp param3)
		throws java.rmi.RemoteException,FoursoftException;
	public  java.util.ArrayList getUserLogViewAllDetails(java.lang.String param0, java.sql.Timestamp param1, java.sql.Timestamp param2)
		throws java.rmi.RemoteException,FoursoftException;
	public  java.util.ArrayList getUserViewAllInformation()	throws java.rmi.RemoteException,FoursoftException;
	public  java.util.ArrayList getUserViewAllInformation(String locationId)	throws java.rmi.RemoteException,FoursoftException;  
	public  java.util.HashMap getWarehousesAndRoles(java.lang.String param0, java.lang.String param1)
		throws java.rmi.RemoteException,FoursoftException;
	public  boolean isMaxLimitNotExceeded()
		throws java.rmi.RemoteException, FoursoftException;
	public  void registerRole(com.foursoft.esupply.accesscontrol.java.RoleModel param0, java.lang.String param1, java.lang.String param2)
		throws java.rmi.RemoteException, com.foursoft.esupply.accesscontrol.exception.AlreadyExistsException, FoursoftException;
	public  void registerUser(com.foursoft.esupply.accesscontrol.java.UserModel param0, java.lang.String param1, java.lang.String param2, java.lang.String param3)
		throws java.rmi.RemoteException, com.foursoft.esupply.accesscontrol.exception.AlreadyExistsException, FoursoftException;
	public  boolean removeUser(java.lang.String param0, java.lang.String param1, java.lang.String param2, java.lang.String param3)
		throws java.rmi.RemoteException, com.foursoft.esupply.accesscontrol.exception.NotExistsException, FoursoftException;
	public  void updateRoleModel(com.foursoft.esupply.accesscontrol.java.RoleModel param0, java.lang.String param1, java.lang.String param2)
		throws java.rmi.RemoteException, FoursoftException,DataIntegrityViolationException;
	public  void updateUserInformation(com.foursoft.esupply.accesscontrol.java.UserModel param0, java.lang.String param1, java.lang.String param2)
		throws java.rmi.RemoteException, com.foursoft.esupply.accesscontrol.exception.NotExistsException,com.foursoft.esupply.accesscontrol.exception.AlreadyExistsException, FoursoftException, com.foursoft.esupply.accesscontrol.exception.DataIntegrityViolationException;
    public ArrayList getLocationIds(String locationId) throws  FoursoftException, RemoteException;

    String upDateUserWithPassword(String userId, String locationId,String ipAddress) throws RemoteException, FoursoftException;

   public void updateSecuritySettings(ArrayList settings) throws FoursoftException, RemoteException;

    String resetUserPassword(String userId, String locationId,String pwd, String email) throws FoursoftException,NotExistsException, RemoteException;

    ArrayList getUserIds(String locationId, String filterString) throws FoursoftException, RemoteException;
	
	public boolean IsLocIdExists( String locationId, String userType, String accessType,String custlocId) throws FoursoftException,NotExistsException, RemoteException;

	public boolean isLocationIdExists(String locationId, String accessType) throws FoursoftException, RemoteException,com.foursoft.esupply.accesscontrol.exception.NotExistsException;
	
	public ArrayList getSecuritySettings() throws FoursoftException,RemoteException;
  
  public ArrayList getRepOfficersIds(String filterString) throws FoursoftException,RemoteException;
  //@@ Added by subrahmanyam for the Enhancement 154384 on 28/01/09
  public ArrayList getSalesPersons(String locationId, String delSalesPerson, String accessTerminal)throws FoursoftException,RemoteException;
  public void updateSalesPerson(String newSalesPerson, String delSalesPerson,String accessType)throws FoursoftException,RemoteException;
  public String getDelSalesPerson(String delUserId)throws FoursoftException,RemoteException;
//@@ Ended by subrahmanyam for the Enhancement 154384 on 28/01/09
  public  java.util.ArrayList getUserViewAllInformation2(String locationId)	throws java.rmi.RemoteException,FoursoftException;
}
