package com.foursoft.esupply.accesscontrol.ejb.sls;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* RemoteInterface Class of the com.foursoft.esupply.accesscontrol.ejb.sls.UserRoleRegistrationSessionBean *
* Thu Mar 06 11:13:56 IST 2003
* ***********************************************/

import javax.ejb.*;
import com.foursoft.esupply.common.exception.FoursoftException;
import com.foursoft.esupply.accesscontrol.exception.NotExistsException;
import com.foursoft.esupply.accesscontrol.exception.DataIntegrityViolationException;
import java.util.ArrayList;

public interface UserRoleRegistrationSessionLocal extends EJBLocalObject
{
	public boolean removeRole(String param0, String param1, String param2, String param3) throws DataIntegrityViolationException, FoursoftException;
	public java.util.ArrayList getRolePermissions(String param0, String param1) throws FoursoftException;
	public int changePassword(String param0, String param1, String param2, String param3,String param4) throws FoursoftException;
	public java.util.Hashtable getAllRolePermissions(String param0, String param1) throws FoursoftException;
	public java.util.ArrayList getLocationIds(String param0, String param1, String param2, String param3) throws FoursoftException;
	public java.util.ArrayList getRoleIdLocDescription(String param0, String param1, String param2) throws FoursoftException;
	public java.util.ArrayList getRoleIdLocation(String param0, String param1, String param2, String param3, String param4, String param5, String param6) throws FoursoftException;
	public java.util.ArrayList getRoleIds(String param0, String param1, String param2) throws FoursoftException;
	public com.foursoft.esupply.accesscontrol.java.RoleModel getRoleModel(String param0, String param1) throws FoursoftException,NotExistsException;
	public java.util.ArrayList getRoleViewAllInformation()	throws FoursoftException;
	public java.util.ArrayList getRoleViewAllInformation(String locationId)	throws FoursoftException;
	public java.util.ArrayList getTransactionDetailVOBs(String param0, String param1) throws FoursoftException;
	public java.util.ArrayList getTransactionDetailVOBs(String param0, int param1, String param2) throws FoursoftException;
	public java.util.ArrayList getTransactionDetailVOBs(String param0) throws FoursoftException;
	public java.util.Hashtable getTransactionIdAndDescription(String param0) throws FoursoftException;
	public  java.util.Hashtable getTransactionIdAndDescription() throws FoursoftException;
	public java.util.ArrayList getTransactionIds(String param0, int param1, String param2) throws FoursoftException;
	public java.util.ArrayList getTransactionIds() throws FoursoftException;
	public java.util.ArrayList getTransactionIds(String param0, String param1) throws FoursoftException;
	public java.util.ArrayList getTransactionIds(String param0) throws FoursoftException;
  //Commented by subrahmanyam for enhancement 154384 on 10/04/09   
	//public java.util.ArrayList getUserIds(String param0, String param1, String param2) throws FoursoftException;
//Added by subrahmanyam for enhancement 154384 on 10/04/09       
  public java.util.ArrayList getUserIds(String param0, String param1, String param2,String param3,String param4) throws FoursoftException;
	public java.util.ArrayList getUserIds(String param0) throws FoursoftException;
	public com.foursoft.esupply.accesscontrol.java.UserModel getUserInformation(String param0, String param1) throws NotExistsException,FoursoftException;
	public java.util.ArrayList getUserLogDetails(String param0, String param1, java.sql.Timestamp param2, java.sql.Timestamp param3) throws FoursoftException;
	public java.util.ArrayList getUserLogViewAllDetails(String param0, java.sql.Timestamp param1, java.sql.Timestamp param2) throws FoursoftException;
	public java.util.ArrayList getUserViewAllInformation()	throws FoursoftException;
	public java.util.ArrayList getUserViewAllInformation(String locationId)	throws FoursoftException;
	public java.util.HashMap getWarehousesAndRoles(String param0, String param1) throws FoursoftException;
	public boolean isMaxLimitNotExceeded() throws FoursoftException;
	public void registerRole(com.foursoft.esupply.accesscontrol.java.RoleModel param0, String param1, String param2) throws com.foursoft.esupply.accesscontrol.exception.AlreadyExistsException, FoursoftException;
	public void registerUser(com.foursoft.esupply.accesscontrol.java.UserModel param0, String param1, String param2, java.lang.String param3) throws com.foursoft.esupply.accesscontrol.exception.AlreadyExistsException, FoursoftException;
	public boolean removeUser(String param0, String param1, String param2, String param3) throws com.foursoft.esupply.accesscontrol.exception.NotExistsException, FoursoftException;
	public void updateRoleModel(com.foursoft.esupply.accesscontrol.java.RoleModel param0, String param1, String param2) throws FoursoftException, DataIntegrityViolationException;
	public void updateUserInformation(com.foursoft.esupply.accesscontrol.java.UserModel param0, String param1, String param2) throws com.foursoft.esupply.accesscontrol.exception.NotExistsException,com.foursoft.esupply.accesscontrol.exception.AlreadyExistsException, FoursoftException, com.foursoft.esupply.accesscontrol.exception.DataIntegrityViolationException;
    public ArrayList getLocationIds(String locationId) throws FoursoftException;
    String upDateUserWithPassword(String userId, String locationId) throws FoursoftException;

    void updatePasswordDuration(int duration) throws FoursoftException;

    String resetUserPassword(String userId, String locationId) throws FoursoftException,NotExistsException;

    ArrayList getUserIds(String locationId, String filterString) throws FoursoftException;

	public boolean IsLocIdExists( String locationId, String userType, String accessType) throws FoursoftException,NotExistsException;

	public boolean isLocationIdExists(String locationId, String accessType) throws FoursoftException,com.foursoft.esupply.accesscontrol.exception.NotExistsException;
	
	public String getPasswordDuration() throws FoursoftException;
  //@@ Added by subrahmanyam for the Enhancement 154384 on 28/01/09
  public ArrayList getSalesPersons(String locationId, String delSalesPerson,String accessTerminal) throws FoursoftException;
  public void updateSalesPerson(String newSalesPerson,String delSalesPerson,String accessType)throws FoursoftException;
  public String getDelSalesPerson(String delUserId)throws FoursoftException;
//@@ Ended by subrahmanyam for the Enhancement 154384 on 28/01/09
}
