package com.foursoft.esupply.accesscontrol.ejb.sls;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* HomeInterface Class of the com.foursoft.esupply.accesscontrol.ejb.sls.UserRoleRegistrationSessionBean *
* Thu Mar 06 11:13:56 IST 2003
* ***********************************************/

import java.rmi.RemoteException;
import javax.ejb.EJBHome;
import javax.ejb.CreateException;

public interface UserRoleRegistrationSessionHome extends EJBHome
{
	public UserRoleRegistrationSession create() throws CreateException, RemoteException;
}
