package com.foursoft.etrans.common.routeplan.ejb.sls;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* HomeInterface Class of the com.foursoft.etrans.common.routeplan.ejb.sls.ETMultiModeRoutePlanSessionBean *
* Tue Sep 17 18:07:03 IST 2002
* ***********************************************/
/**
 * interface name ETMultiModeRoutePlanSessionHome
 * @author :
 * @version :1.6
 */

public interface ETMultiModeRoutePlanSessionHome extends javax.ejb.EJBHome
{

     // @@ Sreelakshmi KVA removed all declarations as public for TogetherJ
	 com.foursoft.etrans.common.routeplan.ejb.sls.ETMultiModeRoutePlanSession create ()
		throws javax.ejb.CreateException, java.rmi.RemoteException;
	 //@@
}
