package com.foursoft.etrans.common.routeplan.ejb.sls;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* RemoteInterface Class of the com.foursoft.etrans.common.routeplan.ejb.sls.ETMultiModeRoutePlanSessionBean *
* Tue Sep 17 18:07:03 IST 2002
* ***********************************************/

/**
 * interface name ETMultiModeRoutePlanSession
 * @author :
 * @version :1.6
 */

public interface ETMultiModeRoutePlanSession extends javax.ejb.EJBObject
{
	 // @@ Sreelakshmi KVA removed all declarations as public for TogetherJ
	 void updateRoutePlan_Sea( java.lang.String p0, java.lang.String p1,java.lang.String p2,java.lang.String[] p3, java.lang.String[] p4 ) 
		throws java.rmi.RemoteException;
	  boolean addRoutePlan(com.foursoft.etrans.common.routeplan.java.ETMultiModeRoutePlanHdrDOB param0)
		throws java.rmi.RemoteException;
	  void deleteRoutePlan(java.lang.String param0)
		throws java.rmi.RemoteException;
	  java.util.ArrayList getDescriptiveConsoleIds(java.lang.String param0, java.lang.String param1, java.lang.String param2, java.lang.String param3)
		throws java.rmi.RemoteException, java.sql.SQLException;
	  java.lang.String[] getGatewayIds(java.lang.String param0, java.lang.String param1, java.lang.String param2)
		throws java.rmi.RemoteException;
	  java.lang.String[][] getGatewayIds(java.lang.String param0)
		throws java.rmi.RemoteException;
	  java.lang.String[] getMasterDocumentNos(java.lang.String param0, java.lang.String param1, java.lang.String param2, java.lang.String param3)
		throws java.rmi.RemoteException;
	  com.foursoft.etrans.common.routeplan.java.ETMultiModeRoutePlanHdrDOB getRoutePlan(java.lang.String param0, java.lang.String param1)
		throws java.rmi.RemoteException;
	  java.lang.String[] getTerminalIds(java.lang.String param0, java.lang.String param1)
		throws java.rmi.RemoteException;
  boolean isValidDocumentNo(java.lang.String param0, java.lang.String param1, java.lang.String param2,java.lang.String param3, java.lang.String param4)
		throws java.rmi.RemoteException;
	  java.lang.String isValidRoutePlan(com.foursoft.etrans.common.routeplan.java.ETMultiModeRoutePlanHdrDOB param0)
		throws java.rmi.RemoteException;
	  boolean removeRoutePlan(java.lang.String param0, java.lang.String param1)
		throws java.rmi.RemoteException;
	  void updateRoutePlan(java.lang.String param0, java.lang.String param1, java.lang.String param2, java.lang.String[] param3, java.lang.String[] param4)
		throws java.rmi.RemoteException;
	  boolean updateRoutePlan(com.foursoft.etrans.common.routeplan.java.ETMultiModeRoutePlanHdrDOB param0)
		throws java.rmi.RemoteException;
	//  boolean updateRoutePlan(com.foursoft.etrans.common.routeplan.java.ETMultiModeRoutePlanHdrDOB param0, java.lang.String param1) 		throws java.rmi.RemoteException;

   boolean updateRoutePlan(com.foursoft.etrans.common.routeplan.java.ETMultiModeRoutePlanHdrDOB p0, String p1, String p2, String p3) throws java.rmi.RemoteException;
   java.util.ArrayList getQuoteIds(java.lang.String param0,java.lang.String param1,java.lang.String param2)throws java.rmi.RemoteException;   java.util.ArrayList getTerminalLocation(java.lang.String param0,java.lang.String param1,java.lang.String param2)throws java.rmi.RemoteException;
   
   java.util.ArrayList getRoutePlanDetails(java.lang.String param0,com.foursoft.esupply.common.bean.ESupplyGlobalParameters loginBean)throws java.rmi.RemoteException;
   boolean updateRoutePlan(java.util.ArrayList param0,String param1,com.foursoft.esupply.common.bean.ESupplyGlobalParameters param2)throws java.rmi.RemoteException;
   java.lang.StringBuffer validateSellRatesHdrData(String[] param0,String[] param1,String[] param2)throws java.rmi.RemoteException;
   //@@
}
