package com.foursoft.esupply.common.ejb.sls;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* RemoteInterface Class of the com.foursoft.esupply.common.ejb.sls.CountryManagerBean *
* Mon Oct 21 16:04:19 IST 2002
* ***********************************************/

import javax.ejb.EJBLocalObject;
import com.foursoft.esupply.common.java.CountryMasterDOB;

public interface CountryManagerLocal extends EJBLocalObject
{
	public  String getCurrencyId(String param0);
	public  java.util.ArrayList getCountryIds(String param0);
	public  void deleteCountry(String param0, String param1, java.sql.Timestamp param2, String param3);
	public  java.util.ArrayList getCountries(String param0);
	public  java.util.ArrayList getCountryDetails(String param0);
	public  void insertCountry(String param0, String param1, java.sql.Timestamp param2, CountryMasterDOB param3);
	public  void updateCountry(String param0, String param1, java.sql.Timestamp param2, CountryMasterDOB param3);
}
