package com.foursoft.esupply.common.ejb.sls;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* RemoteInterface Class of the com.foursoft.esupply.common.ejb.sls.CountryManagerBean *
* Mon Oct 21 16:04:19 IST 2002
* ***********************************************/

import java.rmi.RemoteException;
import javax.ejb.*;

public interface CountryManager extends javax.ejb.EJBObject
{
	public  String getCurrencyId(String param0)
		throws java.rmi.RemoteException;
	public  java.util.ArrayList getCountryIds(String param0)
		throws java.rmi.RemoteException;
	public  void deleteCountry(String param0, String param1, java.sql.Timestamp param2, String param3)
		throws java.rmi.RemoteException;
	public  java.util.ArrayList getCountries(String param0)
		throws java.rmi.RemoteException;
	public  java.util.ArrayList getCountryDetails(String param0)
		throws java.rmi.RemoteException;
	public  void insertCountry(String param0, String param1, java.sql.Timestamp param2, com.foursoft.esupply.common.java.CountryMasterDOB param3)
		throws java.rmi.RemoteException;
	public  void updateCountry(String param0, String param1, java.sql.Timestamp param2, com.foursoft.esupply.common.java.CountryMasterDOB param3)
		throws java.rmi.RemoteException;
}
