package com.foursoft.esupply.common.ejb.sls;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* RemoteInterface Class of the com.foursoft.esupply.common.ejb.sls.MailerBean *
* Mon Oct 21 16:05:05 IST 2002
* ***********************************************/

import java.rmi.RemoteException;
import javax.ejb.*;

public interface Mailer extends javax.ejb.EJBObject
{
	public  void sendMail(com.foursoft.esupply.common.java.EMailMessage param0)
		throws java.rmi.RemoteException;
}
