package com.foursoft.esupply.common.ejb.sls;

/* **********************************************
* Generated by Pramati Technologies, EJBWizard 
* HomeInterface Class of the com.foursoft.esupply.common.ejb.sls.MailerBean *
* Mon Oct 21 16:05:05 IST 2002
* ***********************************************/

import javax.ejb.EJBLocalHome;
import javax.ejb.CreateException;

public interface MailerLocalHome extends EJBLocalHome
{
	public MailerLocal create() throws CreateException;
}
